"use client";
import { useState } from "react";
import { AccountGate } from "../../../components/account-gate";
import { AdminShell } from "../../../components/admin-shell";
import { RefreshButton, ResourceFeedback, useResource } from "../../../components/rewards/resource";
import { api, type Profile } from "../../../lib/api";

type Role = { id: string; key: string; name: string; permissions: string[]; _count: { users: number } };
type StaffUser = { id: string; name: string; email: string; status: string; roles: { role: { key: string; name: string } }[] };
type StaffData = { roles: Role[]; staff: StaffUser[]; availablePermissions: string[] };
const permissionLabels: Record<string, string> = { "users.read": "View user accounts", "users.manage": "Edit user accounts and balances", "chat.manage": "Reply to support chats", "audit.read": "View audit history", "rewards.manage": "Manage tasks, payments, and rewards" };

function Staff({ profile }: { profile: Profile }) {
  const [search, setSearch] = useState(""); const [query, setQuery] = useState("");
  const resource = useResource<StaffData>(`/admin/staff?search=${encodeURIComponent(query)}`);
  const [editor, setEditor] = useState<Role | "new" | null>(null); const [name, setName] = useState(""); const [selectedPermissions, setSelectedPermissions] = useState<string[]>([]);
  const [target, setTarget] = useState<StaffUser | null>(null); const [roleKey, setRoleKey] = useState("user"); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  function edit(role: Role | "new") { setEditor(role); setTarget(null); setName(role === "new" ? "" : role.name); setSelectedPermissions(role === "new" ? [] : role.permissions.filter(key => key !== "profile.manage")); setReason(""); setError(""); }
  async function saveRole(event: React.FormEvent) { event.preventDefault(); if (!editor) return; setBusy(true); setError(""); try { await api(`/admin/staff/roles${editor === "new" ? "" : "/" + editor.id}`, { method: editor === "new" ? "POST" : "PATCH", body: JSON.stringify({ name, permissions: selectedPermissions, reason }) }); setMessage(editor === "new" ? "Staff role created." : "Staff role updated. Assigned staff must sign in again."); setEditor(null); await resource.refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function assign(event: React.FormEvent) { event.preventDefault(); if (!target) return; setBusy(true); setError(""); try { await api(`/admin/staff/users/${target.id}`, { method: "PATCH", body: JSON.stringify({ roleKey, reason }) }); setMessage("Access updated. This account must sign in again."); setTarget(null); await resource.refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><div className="ad-page-title"><div><span className="eyebrow">SUPER ADMIN</span><h1>Staff access</h1><p>Give staff only the controls they need. Changes are recorded and take effect on their next sign-in.</p></div><RefreshButton onClick={resource.refresh} busy={resource.loading}/></div><ResourceFeedback {...resource} retry={resource.refresh} initial={!resource.data}/>{message && <p className="form-success" role="status">{message}</p>}
    <section className="panel ad-section"><div className="section-top"><div><h2>Roles</h2><p>Custom roles can use the permissions below. Super Admin and Admin are fixed roles.</p></div><button className="rw-button rw-button-primary" onClick={() => edit("new")}>Create staff role</button></div><div className="ad-staff-roles">{resource.data?.roles.map(role => <article key={role.id}><div><strong>{role.name}</strong><small>{role._count.users} assigned</small></div><p>{role.permissions.filter(key => key !== "profile.manage").join(" · ") || "Profile access only"}</p>{role.key.startsWith("staff_") && <button className="rw-button rw-button-secondary" onClick={() => edit(role)}>Edit permissions</button>}</article>)}</div></section>
    <section className="panel ad-section"><div className="section-top"><div><h2>Assign staff access</h2><p>Search an account by name or email, then choose its role.</p></div></div><form className="ad-toolbar" onSubmit={event => { event.preventDefault(); setQuery(search.trim()); }}><input aria-label="Find a user for staff access" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name or email"/><button className="rw-button rw-button-secondary">Search</button></form><div className="ad-staff-list">{resource.data?.staff.map(user => <article key={user.id}><div><strong>{user.name}</strong><small>{user.email} · {user.status}</small><span>{user.roles.filter(entry => entry.role.key !== "user").map(entry => entry.role.name).join(", ") || "User"}</span></div>{!user.roles.some(entry => entry.role.key === "super_admin") && user.id !== profile.user.id && <button className="rw-button rw-button-secondary" onClick={() => { setEditor(null); setTarget(user); setRoleKey(user.roles.find(entry => entry.role.key !== "user")?.role.key || "user"); setReason(""); setError(""); }}>Change role</button>}</article>)}</div>{query && resource.data?.staff.length === 0 && <p>No matching account found.</p>}</section>
    {editor && <section className="panel ad-section ad-staff-editor"><h2>{editor === "new" ? "Create a staff role" : `Edit ${editor.name}`}</h2><form className="profile-form" onSubmit={saveRole}><label>Role name<input value={name} onChange={event => setName(event.target.value)} minLength={3} maxLength={60} required/></label><fieldset><legend>Allowed permissions</legend>{resource.data?.availablePermissions.map(permission => <label className="rw-check-field" key={permission}><input type="checkbox" checked={selectedPermissions.includes(permission)} onChange={event => setSelectedPermissions(event.target.checked ? [...selectedPermissions, permission] : selectedPermissions.filter(key => key !== permission))}/>{permissionLabels[permission] || permission}</label>)}</fieldset><label>Reason for change<textarea value={reason} onChange={event => setReason(event.target.value)} minLength={10} maxLength={500} required/></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="rw-inline-actions"><button className="rw-button rw-button-primary" disabled={busy}>{busy ? "Saving..." : "Save role"}</button><button type="button" className="rw-button rw-button-secondary" onClick={() => setEditor(null)} disabled={busy}>Cancel</button></div></form></section>}
    {target && <section className="panel ad-section ad-staff-editor"><h2>Access for {target.name}</h2><form className="profile-form" onSubmit={assign}><label>Role<select value={roleKey} onChange={event => setRoleKey(event.target.value)}><option value="user">User — remove staff access</option>{resource.data?.roles.filter(role => role.key !== "super_admin").map(role => <option value={role.key} key={role.key}>{role.name}</option>)}</select></label><label>Reason for change<textarea value={reason} onChange={event => setReason(event.target.value)} minLength={10} maxLength={500} required/></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="rw-inline-actions"><button className="rw-button rw-button-primary" disabled={busy}>{busy ? "Saving..." : "Update access"}</button><button type="button" className="rw-button rw-button-secondary" onClick={() => setTarget(null)} disabled={busy}>Cancel</button></div></form></section>}
  </AdminShell>;
}
export default function Page() { return <AccountGate>{profile => profile.permissions.includes("roles.manage") ? <Staff profile={profile}/> : <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><p>Super admin access required.</p></AdminShell>}</AccountGate>; }
