"use client";
import { useState } from "react";
import { usePathname } from "next/navigation";
import { ClipboardCheck, Plus, Settings2 } from "lucide-react";
import { AccountGate } from "../../../components/account-gate";
import { AdminShell } from "../../../components/admin-shell";
import { Modal } from "../../../components/rewards/primitives";
import { Pagination, RefreshButton, ResourceFeedback, useResource } from "../../../components/rewards/resource";
import { api, type Profile } from "../../../lib/api";
import { money, points, paymentStatus, type Rules, type Task, type TaskRun, type Withdrawal } from "../../../lib/rewards";

type Review = TaskRun & { task: { title: string }; user: { name: string; email: string } };
type RequestRow = Withdrawal & { user: { name: string; email: string; withdrawalEligible: boolean } };
type Overview = { rules: Rules; tasks: Task[]; reviews: Review[]; withdrawals: RequestRow[]; reviewCount: number; withdrawalCount: number };
type TaskEdit = Omit<Task, "run" | "slotsRemaining">;
function AdminRewards({ profile }: { profile: Profile }) {
  const path = usePathname();
  const [page, setPage] = useState(1);
  const resource = useResource<Overview>(`/admin/rewards?page=${page}`);
  const initialTab = path.endsWith("/tasks") ? "tasks" : path.endsWith("/withdrawals") ? "withdrawals" : path.endsWith("/settings") ? "settings" : "reviews";
  const [tab, setTab] = useState(initialTab); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [editor, setEditor] = useState<TaskEdit | null>(null);
  const [decision, setDecision] = useState<{ kind: "reviews" | "withdrawals"; id: string; action: string; title: string } | null>(null);
  const [reason, setReason] = useState(""); const [paymentReference, setPaymentReference] = useState("");
  const [issuedCode, setIssuedCode] = useState("");
  const data = resource.data;
  async function mutate(path: string, body: unknown, method = "POST") {
    if (busy) return false; setBusy(true); setError(""); setMessage("");
    try { await api(`/admin/rewards${path}`, { method, body: JSON.stringify(body) }); await resource.refresh(); setMessage("Saved. The change is recorded in the audit log."); return true; }
    catch (e) { setError((e as Error).message); return false; }
    finally { setBusy(false); }
  }
  function newTask() { setError(""); setEditor({ id: "", title: "", description: "", instructions: "", category: "Feedback", rewardPoints: 1500, verification: "manual", destinationUrl: null, active: true, startsAt: new Date().toISOString(), endsAt: null, dailyLimit: 100, totalLimit: 10000 }); }
  async function saveTask(e: React.FormEvent) {
    e.preventDefault(); if (!editor) return;
    const body = { title: editor.title, description: editor.description, instructions: editor.instructions, category: editor.category, rewardPoints: Number(editor.rewardPoints), verification: editor.verification, destinationUrl: editor.destinationUrl || null, active: editor.active, startsAt: editor.startsAt, endsAt: editor.endsAt || null, dailyLimit: Number(editor.dailyLimit), totalLimit: Number(editor.totalLimit) };
    if (await mutate(`/tasks${editor.id ? `/${editor.id}` : ""}`, body, editor.id ? "PATCH" : "POST")) setEditor(null);
  }
  async function issueCode(id: string) {
    if (busy) return; setBusy(true); setError("");
    try { const result = await api<{ code: string }>(`/admin/rewards/tasks/${id}/codes`, { method: "POST", body: "{}" }); setIssuedCode(result.code); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  const decide = (kind: "reviews" | "withdrawals", id: string, action: string, title: string) => { setError(""); setReason(""); setPaymentReference(""); setDecision({ kind, id, action, title }); };
  return <AdminShell name={profile.user.name}><div className="ad-page-title"><div><span className="eyebrow">TASKS, REVIEWS & PAYOUTS</span><h1>{tab === "tasks" ? "Task management" : tab === "withdrawals" ? "Withdrawal approvals" : tab === "settings" ? "Rules and settings" : "Verification review"}</h1><p>Manage user reward operations with a complete audit trail.</p></div><RefreshButton onClick={resource.refresh} busy={resource.loading} /></div>
    <ResourceFeedback {...resource} retry={resource.refresh} initial={!data} />{error && !decision && !editor && <div className="form-error" role="alert">{error}</div>}{message && <div className="form-success" role="status">{message}</div>}
    <div className="rw-task-filters" role="group" aria-label="Reward administration">{["reviews", "tasks", "withdrawals", "settings"].map(t => <button key={t} aria-pressed={tab === t} className={tab === t ? "is-active" : ""} onClick={() => setTab(t)}>{t === "reviews" ? `Proof review (${data?.reviewCount || 0})` : t === "withdrawals" ? `Withdrawals (${data?.withdrawalCount || 0})` : t[0].toUpperCase() + t.slice(1)}</button>)}</div>
    {data && <>
      {tab === "reviews" && <section className="panel"><div className="section-top"><h2>Awaiting review</h2><ClipboardCheck size={22} /></div>{data.reviews.length === 0 && <p>No submissions awaiting review on this page.</p>}{data.reviews.map(review => <article className="rw-admin-review" key={review.id}><h3>{review.task.title}</h3><p>{review.user.name} · {review.user.email} · {points(review.rewardPoints)} pts</p><blockquote className="rw-proof-text">{review.proof}</blockquote><div className="rw-inline-actions"><button className="rw-button rw-button-primary" disabled={busy} onClick={() => decide("reviews", review.id, "approve", review.task.title)}>Approve proof</button><button className="rw-button rw-button-secondary" disabled={busy} onClick={() => decide("reviews", review.id, "reject", review.task.title)}>Request correction</button></div></article>)}<Pagination page={page} total={Math.max(data.reviewCount, data.withdrawalCount)} onPage={setPage} busy={resource.loading} /></section>}
      {tab === "tasks" && <section className="panel"><div className="section-top"><h2>Published tasks</h2><button className="rw-button rw-button-primary" onClick={newTask}><Plus size={17} />Create task</button></div>{data.tasks.length === 0 && <p>Create your first approved task to make it available to users.</p>}{data.tasks.map(task => <article className="rw-admin-review" key={task.id}><div className="section-top"><h3>{task.title}</h3><span className={`rw-state-badge ${task.active ? "available" : "rejected"}`}>{task.active ? "Active" : "Paused"}</span></div><p>{points(task.rewardPoints)} pts · {task.verification === "code" ? "Unique code" : "Manual proof"} · {task.dailyLimit} daily slots</p><div className="rw-inline-actions"><button className="rw-button rw-button-secondary" onClick={() => { setError(""); setEditor(task); }}>Edit task</button>{task.verification === "code" && <button className="rw-button rw-button-secondary" disabled={busy} onClick={() => issueCode(task.id)}>Issue completion code</button>}</div></article>)}</section>}
      {tab === "withdrawals" && <section className="panel"><h2>Withdrawal queue</h2><div className="rw-notice"><p>Requests reserve the selected balance immediately. Approval does not send money. After making a payment through your provider, record its reference here. Rejecting releases the reserved points or deposited USD. Do not mark a request paid before sending the payment.</p></div>{data.withdrawals.length === 0 && <p>No open requests on this page.</p>}{data.withdrawals.map(w => <article className="rw-admin-review" key={w.id}><div className="section-top"><h3>{money(w.amountCents)} · {w.provider.toUpperCase()}</h3><span className={`rw-state-badge ${w.status}`}>{paymentStatus(w.status)}</span></div><p>{w.user.name} · {w.user.email}</p><p className="rw-proof-text">{w.destination}</p><small>{w.source === "deposit" ? `${money(w.amountCents)} reserved USD from deposits` : `${points(w.points)} reserved points`} · {w.user.withdrawalEligible ? "Eligible" : "Eligibility on hold"}</small><div className="rw-inline-actions">{w.status === "pending" ? <button disabled={busy} className="rw-button rw-button-primary" onClick={() => decide("withdrawals", w.id, "approve", `${money(w.amountCents)} withdrawal`)}>Approve request</button> : <button disabled={busy} className="rw-button rw-button-primary" onClick={() => decide("withdrawals", w.id, "paid", `${money(w.amountCents)} payment`)}>Record completed payment</button>}<button disabled={busy} className="rw-button rw-button-secondary" onClick={() => decide("withdrawals", w.id, "reject", `${money(w.amountCents)} withdrawal`)}>Reject & release balance</button></div></article>)}<Pagination page={page} total={Math.max(data.reviewCount, data.withdrawalCount)} onPage={setPage} busy={resource.loading} /></section>}
      {tab === "settings" && <div className="profile-grid"><section className="panel"><div className="section-top"><h2>Reward rules</h2><Settings2 size={21} /></div><p>Rate changes affect available points. Existing withdrawals keep their quoted rate; existing referrals keep their registration terms.</p><form className="profile-form" key={JSON.stringify(data.rules)} onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const values = new FormData(form); if (await mutate("/settings", { pointsPerUsd: Number(values.get("pointsPerUsd")), minWithdrawalCents: Number(values.get("minWithdrawalCents")), maxWithdrawalCents: Number(values.get("maxWithdrawalCents")), referralRewardPoints: Number(values.get("referralRewardPoints")), referralRequiredTasks: Number(values.get("referralRequiredTasks")), referralsEnabled: values.get("referralsEnabled") === "on", reason: values.get("reason") }, "PATCH")) form.reset(); }}>
        {([["pointsPerUsd", "Points per $1 USD", 1, 1000000], ["minWithdrawalCents", "Minimum withdrawal (USD cents)", 1, 1000000], ["maxWithdrawalCents", "Maximum withdrawal (USD cents)", 1, 1000000], ["referralRewardPoints", "Points per qualified referral", 0, 1000000], ["referralRequiredTasks", "Claimed tasks to qualify a referral", 1, 1000]] as const).map(([key, label, min, max]) => <label key={key}>{label}<input name={key} type="number" defaultValue={data.rules[key]} min={min} max={max} step={1} required disabled={busy} /></label>)}<label className="rw-check-field"><input type="checkbox" name="referralsEnabled" defaultChecked={data.rules.referralsEnabled} disabled={busy} />Accept new referrals</label><label>Reason for changes<input name="reason" minLength={10} maxLength={500} required disabled={busy} /></label><button className="rw-button rw-button-primary" disabled={busy}>{busy ? "Saving…" : "Save reward rules"}</button></form></section>
        <section className="panel"><h2>Withdrawal eligibility</h2><p>Allow or hold withdrawals for an individual user. Each change requires a recorded reason.</p><form className="profile-form" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const v = new FormData(form); if (await mutate("/eligibility", { email: v.get("email"), eligible: v.get("eligible") === "yes", reason: v.get("reason") }, "PATCH")) form.reset(); }}><label>User email<input type="email" name="email" required disabled={busy} /></label><label>Eligibility<select name="eligible" disabled={busy}><option value="yes">Allow withdrawals</option><option value="no">Hold withdrawals</option></select></label><label>Reason<input name="reason" minLength={10} maxLength={500} required disabled={busy} /></label><button className="rw-button rw-button-primary" disabled={busy}>Update eligibility</button></form></section></div>}
    </>}
    {decision && <Modal title={`${decision.action} ${decision.title}`} onClose={() => { if (!busy) setDecision(null); }}><span className="rw-tag">RECORDED REVIEW</span><h2>{decision.action === "paid" ? "Record completed payment" : decision.action === "approve" ? "Approve" : "Reject"}</h2><p>{decision.title}</p><form className="profile-form" onSubmit={async e => { e.preventDefault(); if (await mutate(`/${decision.kind}/${decision.id}`, { decision: decision.action, reason, ...(decision.action === "paid" ? { paymentReference } : {}) })) setDecision(null); }}><label>Reason / feedback<textarea rows={3} value={reason} onChange={e => setReason(e.target.value)} minLength={10} maxLength={500} required disabled={busy} /></label>{decision.action === "paid" && <label>Provider payment reference<input value={paymentReference} onChange={e => setPaymentReference(e.target.value)} required minLength={5} maxLength={150} disabled={busy} /></label>}{error && <div className="form-error" role="alert">{error}</div>}<button className="rw-button rw-button-primary" disabled={busy}>{busy ? "Saving…" : "Confirm review"}</button></form></Modal>}
    {issuedCode && <Modal title="Unique completion code" onClose={() => setIssuedCode("")}><h2>One completion. One code.</h2><p>Give this code only after the participant completes the task. It is displayed once and can be redeemed by one user.</p><input className="rw-code-output" aria-label="Issued completion code" readOnly value={issuedCode} onFocus={e => e.target.select()} /><button className="rw-button rw-button-primary rw-full" onClick={() => setIssuedCode("")}>Done</button></Modal>}
    {editor && <Modal title={editor.id ? "Edit task" : "Create task"} onClose={() => { if (!busy) setEditor(null); }}><h2>{editor.id ? "Edit task" : "A new opportunity."}</h2><p>Participants keep the reward and verification method assigned when they start. Pausing stops new starts.</p><form className="profile-form" onSubmit={saveTask}><label>Title<input value={editor.title} onChange={e => setEditor({ ...editor, title: e.target.value })} minLength={3} maxLength={120} required /></label><label>Description<textarea value={editor.description} onChange={e => setEditor({ ...editor, description: e.target.value })} minLength={10} maxLength={500} required /></label><label>Instructions<textarea rows={5} value={editor.instructions} onChange={e => setEditor({ ...editor, instructions: e.target.value })} minLength={10} maxLength={4000} required /></label><label>Category<select value={editor.category} onChange={e => setEditor({ ...editor, category: e.target.value })}>{["Website", "Video", "App", "Survey", "Feedback", "Other"].map(c => <option key={c}>{c}</option>)}</select></label><label>Reward points<input type="number" min={1} max={1000000} required value={editor.rewardPoints} onChange={e => setEditor({ ...editor, rewardPoints: Number(e.target.value) })} /></label><label>Verification<select value={editor.verification} onChange={e => setEditor({ ...editor, verification: e.target.value as "code" | "manual" })}><option value="manual">Manual proof review</option><option value="code">Unique completion code</option></select></label><label>Task website (optional)<input type="url" value={editor.destinationUrl || ""} onChange={e => setEditor({ ...editor, destinationUrl: e.target.value || null })} /></label><label>Starts at (UTC)<input type="datetime-local" value={editor.startsAt.slice(0, 16)} onChange={e => setEditor({ ...editor, startsAt: e.target.value ? new Date(e.target.value + "Z").toISOString() : "" })} required /></label><label>Ends at (UTC, optional)<input type="datetime-local" value={editor.endsAt?.slice(0, 16) || ""} onChange={e => setEditor({ ...editor, endsAt: e.target.value ? new Date(e.target.value + "Z").toISOString() : null })} /></label><div className="rw-form-columns"><label>Daily slots<input type="number" min={1} max={1000000} value={editor.dailyLimit} onChange={e => setEditor({ ...editor, dailyLimit: Number(e.target.value) })} required /></label><label>Total slots<input type="number" min={1} max={10000000} value={editor.totalLimit} onChange={e => setEditor({ ...editor, totalLimit: Number(e.target.value) })} required /></label></div><label className="rw-check-field"><input type="checkbox" checked={editor.active} onChange={e => setEditor({ ...editor, active: e.target.checked })} />Active / accepting new starts</label>{error && <div className="form-error" role="alert">{error}</div>}<button className="rw-button rw-button-primary" disabled={busy}>{busy ? "Saving…" : "Save task"}</button></form></Modal>}
  </AdminShell>;
}
export default function Page() { return <AccountGate>{profile => profile.permissions.includes("rewards.manage") ? <AdminRewards profile={profile} /> : <AdminShell name={profile.user.name}><div className="form-error" role="alert">You do not have permission to manage rewards.</div></AdminShell>}</AccountGate>; }
