"use client";
import { useEffect, useState } from "react";
import type { SurveyAnswer, SurveyQuestion } from "../../lib/rewards";
import { readDraft, saveDraft } from "../../lib/task-draft";
export function SurveyForm({ questions, initialAnswers, draftKey, instant = false, busy, onSubmit }: { questions: SurveyQuestion[]; draftKey: string; instant?: boolean; initialAnswers?: SurveyAnswer[] | null; busy: boolean; onSubmit: (answers: SurveyAnswer[]) => void }) {
 const [answers, setAnswers] = useState<Record<string, string>>(() => ({ ...Object.fromEntries((initialAnswers || []).map(answer => [answer.questionId, answer.answer])), ...readDraft(draftKey).surveyAnswers }));
 useEffect(() => { saveDraft(draftKey, { ...readDraft(draftKey), surveyAnswers: answers }); }, [answers, draftKey]);
 const answered = questions.filter(question => answers[question.id]?.trim()).length;
 return <form className="profile-form" onSubmit={e => { e.preventDefault(); if (!busy && answered === questions.length) onSubmit(questions.map(question => ({ questionId: question.id, answer: answers[question.id] || "" }))); }}><fieldset disabled={busy} className="rw-poll-form-fields"><legend>Your survey answers</legend><p>{answered} of {questions.length} answered</p><progress aria-label="Survey progress" value={answered} max={questions.length || 1} />{questions.map((question, index) => <fieldset className="rw-survey-question" key={question.id}><legend>{index + 1}. {question.prompt}</legend>{question.type === "text" ? <textarea aria-label={question.prompt} value={answers[question.id] || ""} onChange={e => setAnswers(current => ({ ...current, [question.id]: e.target.value }))} required maxLength={2000} rows={3} /> : <div className="rw-survey-choices">{(question.type === "yes_no" ? ["Yes", "No"] : question.options).map(option => <label className="rw-check-field" key={option}><input type="radio" name={question.id} value={option} checked={answers[question.id] === option} onChange={() => setAnswers(current => ({ ...current, [question.id]: option }))} required />{option}</label>)}</div>}</fieldset>)}<button className="rw-button rw-button-primary rw-full" disabled={busy || answered !== questions.length}>{busy ? "Submitting..." : instant ? "Submit survey & earn points" : "Submit survey for approval"}</button></fieldset></form>;
}
