"use client";
import { TaskRepeatInfo } from "./task-repeat-info";
import { ArrowRight, CheckCircle2, ClipboardCheck, Coins, Globe, MessageSquare, Play, ShieldCheck, Smartphone, Star, Music, Package, Image, Heart } from "lucide-react";
import { money, points, taskStatus, type Task } from "../../lib/rewards";
const icons = { Website: Globe, Video: Play, App: Smartphone, Survey: ClipboardCheck, Feedback: MessageSquare, Other: ShieldCheck };
export function TaskTile({ task, rate, onOpen, onFavorite }: { task: Task; rate?: number; onOpen: (task: Task) => void; onFavorite?: (task: Task) => void }) {
 const Icon = task.taskType === "movie_review" ? Star : task.taskType === "music_review" ? Music : task.taskType === "image_preference" ? Image : task.taskType === "product_experience" ? Package : icons[task.category as keyof typeof icons] || ClipboardCheck;
 const cover = task.coverImageUrl || task.coverImage;
 const reward=task.run?.rewardPoints||task.rewardPoints;const complete=task.run?.status==="completed";
 return <article className={"rw-task-tile neon-task-row neon-kind-"+task.taskType+(task.featured?" is-featured":"")}><button className={"rw-favorite-task "+(task.favorite?"is-active":"")} aria-label={task.favorite?"Remove from saved tasks":"Save task"} aria-pressed={!!task.favorite} onClick={()=>onFavorite?.(task)}><Heart size={18} fill={task.favorite?"currentColor":"none"}/></button><div className="neon-task-icon" aria-hidden="true"><Icon size={32}/>{cover&&<img key={cover} src={cover} alt="" loading="lazy" decoding="async" onError={e=>{e.currentTarget.style.display="none";}}/>}</div><div className="neon-task-copy"><span className="neon-task-label">{task.taskType === "standard" ? task.category : task.taskType.replaceAll("_"," ")}</span><h2>{task.title}</h2><p>{task.description}</p><div className="neon-task-meta"><span><ShieldCheck size={14}/>{taskStatus(task)}</span><span>{task.run?"Your place is saved":task.slotsRemaining+" slots today"}</span>{task.autoClaimOnVerification&&<span>Instant reward</span>}</div><TaskRepeatInfo hours={task.repeatHours} nextAt={task.nextAvailableAt} completed={complete}/></div><div className="neon-task-reward"><strong><Coins size={21}/>+{points(reward)}</strong>{rate&&<small>{money(Math.floor(reward*100/rate))} value</small>}<button className={"rw-button "+(complete?"rw-claimed-button":"rw-button-primary")} onClick={()=>onOpen(task)}>{complete?<><CheckCircle2 size={16}/>Completed</>:<>{task.run?.status==="approved"?"Claim points":task.run?"Continue":task.featured?"Open task":"Open"}<ArrowRight size={16}/></>}</button></div></article>;
}
