/* eslint-disable @next/next/no-img-element */
"use client";
import { FeaturedTasks } from "../../components/rewards/featured-tasks";
import { PromotionBanners } from "../../components/rewards/promotion-banners";
import { SurveyForm } from "../../components/rewards/survey-form";
import { MediaReviewForm } from "../../components/rewards/media-review-form";
import { TaskRepeatInfo } from "../../components/rewards/task-repeat-info";
import Link from "next/link";
import { useEffect, useState } from "react";
import { LayoutGrid, Play, Smartphone, Globe, MessageSquare, ArrowLeft, ArrowRight, CheckCircle2, ClipboardCheck, Coins, Search, ShieldCheck, Sparkles, Trophy, XCircle } from "lucide-react";
import { AccountGate } from "../../components/account-gate";
import { Shell } from "../../components/shell";
import { TaskTile } from "../../components/rewards/task-tile";
import { TaskNotifications } from "../../components/task-notifications";
import { AnimatedCounter, Modal } from "../../components/rewards/primitives";
import { RefreshButton, ResourceFeedback, useResource } from "../../components/rewards/resource";
import { imageData } from "../../lib/image-upload";
import { clearDraft, draftKey, loadDraftImage, readDraft, saveDraft, saveDraftImage } from "../../lib/task-draft";
import { api, type Profile } from "../../lib/api";
import { points, taskStatus, type Task, type TaskRun, type Wallet } from "../../lib/rewards";

function TaskPage({ profile }: { profile: Profile }) {
  const tasks = useResource<Task[]>("/tasks?summary=1"); const wallet = useResource<Wallet>("/wallet");
  const [category, setCategory] = useState("All"); const [status, setStatus] = useState("Available"); const [search, setSearch] = useState("");
  const [detail, setDetail] = useState<Task | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null); const [runOverride, setRunOverride] = useState<TaskRun | null>(null);
  const [selectedDesignId, setSelectedDesignId] = useState("");
  const [proofImage, setProofImage] = useState("");
  const membership = useResource<{ hasActiveMembership: boolean }>("/membership");
  const [proof, setProof] = useState(""); const [code, setCode] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [answers, setAnswers] = useState<Record<string, boolean>>({}); const [step, setStep] = useState(0); const [review, setReview] = useState(false); const [success, setSuccess] = useState<{ points: number; title: string } | null>(null);
  const selected = detail?.id === selectedId ? detail : null; const run = runOverride || selected?.run; const all = tasks.data || [];
  const activeDraftKey = run?.status === "in_progress" ? draftKey(profile.user.id, run.id) : null;
  useEffect(() => { if (activeDraftKey) saveDraft(activeDraftKey, { proof, code, answers, selectedDesignId }); }, [activeDraftKey, proof, code, answers, selectedDesignId]);
  const categories = ["All", ...new Set(all.map(task => task.category))];
  const visible = all.filter(task => (category === "All" || task.category === category) && (status === "All" || taskStatus(task) === status) && `${task.title} ${task.description}`.toLowerCase().includes(search.toLowerCase()));
  async function open(task: Task) { if (detailLoading) return; setSelectedDesignId(""); setSelectedId(task.id); setDetail(null); setDetailLoading(true); setRunOverride(null); setCode(""); setAnswers({}); setStep(0); setReview(false); setError(""); setMessage(""); try { const full = await api<Task>("/tasks/" + task.id); setDetail(full); setProofImage(full.run?.proofImage || ""); setProof(full.run?.proof || ""); if (full.run?.status === "in_progress") { const draft = readDraft(draftKey(profile.user.id, full.run.id)); setProof(draft.proof ?? full.run.proof ?? ""); setCode(draft.code ?? ""); setAnswers(draft.answers ?? {}); if (full.taskType === "product_experience") { const nextUnanswered = full.products.findIndex(product => draft.answers?.[product.id] === undefined); setStep(nextUnanswered < 0 ? Math.max(0, full.products.length - 1) : nextUnanswered); setReview(nextUnanswered < 0 && full.products.length > 0); } setSelectedDesignId(draft.selectedDesignId ?? ""); const savedImage = await loadDraftImage(draftKey(profile.user.id, full.run.id)); if (savedImage) setProofImage(savedImage); } } catch (failure) { setError((failure as Error).message); } finally { setDetailLoading(false); } }
  async function call(kind: "start" | "submit" | "claim", body: Record<string, unknown> = {}) { if (!selected) throw new Error("Task not found."); return api<TaskRun | { run: TaskRun; credited: boolean }>(`/tasks/${selected.id}/${kind}`, { method: "POST", body: JSON.stringify({ ...body, ...(kind !== "start" && run?.id ? { runId: run.id } : {}) }) }); }
  async function action(kind: "start" | "submit" | "claim", submittedBody?: Record<string, unknown>) { if (!selected || busy) return; setBusy(true); setError(""); setMessage(""); try { const result = await call(kind, submittedBody || (kind === "submit" ? run?.verification === "code" ? { code } : { ...(proof.length >= 10 ? { proof } : {}), ...(proofImage.startsWith("data:image/") ? { proofImage } : {}) } : {})); const next = "run" in result ? result.run : result; if (kind !== "start") clearDraft(draftKey(profile.user.id, next.id)); setRunOverride(next); if (kind === "claim" || (kind === "submit" && next.status === "completed")) { setSelectedId(null); setSuccess({ points: kind === "submit" ? next.rewardPoints : "credited" in result && result.credited ? next.rewardPoints : 0, title: selected.title }); } else setMessage(kind === "start" ? "Task started. Complete each step below." : next.status === "approved" ? "Verification successful. Your points are ready." : "Proof submitted for review."); await Promise.all([tasks.refresh(), wallet.refresh()]); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  function answer(productId: string, value: boolean) { setAnswers(current => ({ ...current, [productId]: value })); if (selected && step < selected.products.length - 1) setStep(step + 1); else setReview(true); }
  async function completeProducts() { if (!selected || busy || (selected.taskType === "image_preference" ? !selectedDesignId : selected.products.some(product => answers[product.id] === undefined))) return; setBusy(true); setError(""); try { const submitted = await call("submit", selected.taskType === "image_preference" ? { selectedDesignId } : { productAnswers: selected.products.map(product => ({ productId: product.id, answer: answers[product.id] })) }); const submittedRun = "run" in submitted ? submitted.run : submitted; clearDraft(draftKey(profile.user.id, submittedRun.id)); if (submittedRun.status === "pending_review") { setRunOverride(submittedRun); setReview(false); setMessage("Answers submitted. Your reward will be credited automatically after admin approval."); await tasks.refresh(); return; } if (submittedRun.status === "completed") { setSelectedId(null); setSuccess({ points: submittedRun.rewardPoints, title: selected.title }); await Promise.all([tasks.refresh(), wallet.refresh()]); return; } const claimed = await call("claim"); const next = "run" in claimed ? claimed.run : claimed; setSelectedId(null); setSuccess({ points: "credited" in claimed && claimed.credited ? next.rewardPoints : 0, title: selected.title }); await Promise.all([tasks.refresh(), wallet.refresh()]); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const product = selected?.products[step]; const answered = Object.keys(answers).length;
  return <Shell name={profile.user.name} admin={profile.permissions.includes("users.read")}>
    <TaskNotifications />
    {membership.data && !membership.data.hasActiveMembership && <Link className="rw-button rw-button-primary rw-join-tasks" href="/membership">JOIN FOR MORE TASKS<ArrowRight size={18} /></Link>}
    <div className="task-board"><div className="page-heading rw-compact-heading"><div><span className="eyebrow">YOUR DAILY OPPORTUNITIES</span><h1>Make today rewarding.</h1><p>Choose a task, share your thoughts, and earn.</p></div><RefreshButton busy={tasks.loading} onClick={tasks.refresh} /></div>
    <PromotionBanners placement="banner"/><section className="neon-reward-banner"><div><span className="eyebrow">SMALL TASKS. BIG POSSIBILITIES.</span><h2>Complete tasks.<br/><em>Earn real rewards.</em></h2><p>Share your opinions, collect points, and work towards your next reward.</p><Link href="/how-it-works" className="rw-button rw-button-primary"><Play size={17}/>How it works</Link></div><div className="neon-trophy" aria-hidden="true"><Trophy strokeWidth={1.4}/><Sparkles className="neon-spark"/></div></section><section className="task-board-overview"><div><span className="eyebrow">TODAY&apos;S EARNINGS</span><strong>{wallet.data ? points(wallet.data.todayPoints) : "--"}<small>points</small></strong><p>One completed task. One step closer.</p></div><Link href="/wallet" className="rw-button rw-button-secondary">View wallet<ArrowRight size={16} /></Link></section>
    <nav className="task-board-tabs" aria-label="Task status">{["Available", "In Progress", "Pending Review", "Completed", "All"].map(value => <button key={value} aria-pressed={status === value} onClick={() => setStatus(value)}>{value === "All" ? "All tasks" : value}<span>{all.filter(task => value === "All" || taskStatus(task) === value).length}</span></button>)}</nav>
    <div className="rw-module-toolbar"><label className="rw-search"><Search size={18} /><input aria-label="Search tasks" placeholder="Search your next task" value={search} onChange={e => setSearch(e.target.value)} /></label><label className="rw-status-filter">Status<select value={status} onChange={e => setStatus(e.target.value)}>{["All", "Available", "In Progress", "Pending Review", "Completed"].map(value => <option key={value}>{value}</option>)}</select></label></div>
    <div className="rw-task-filters neon-categories">{categories.map(value => { const Icon = ({All:LayoutGrid,App:Smartphone,Video:Play,Survey:ClipboardCheck,Website:Globe,Feedback:MessageSquare} as Record<string,typeof LayoutGrid>)[value] || Sparkles; return <button key={value} aria-pressed={category === value} className={category === value ? "is-active" : ""} onClick={() => setCategory(value)}><Icon size={26}/><span>{value === "All" ? "All tasks" : value}</span></button>; })}</div>
    <ResourceFeedback {...tasks} retry={tasks.refresh} initial={!tasks.data} /><FeaturedTasks tasks={visible.filter(task=>task.featured)} rate={wallet.data?.rules.pointsPerUsd} onOpen={open}/><div className="rw-task-list-heading"><h2>{status === "Available" ? "More tasks for you" : status === "All" ? "All tasks" : status} <span>({visible.filter(task=>!task.featured).length})</span></h2>{wallet.data && <span className="rw-reward-pill">{points(wallet.data.rules.pointsPerUsd)} pts = $1.00</span>}</div>
    <div className="rw-live-task-grid task-board-grid">{visible.filter(task=>!task.featured).map(task => <TaskTile key={task.id} task={task} rate={wallet.data?.rules.pointsPerUsd} onOpen={open} />)}</div>{tasks.data && !visible.length && <div className="panel rw-empty"><ClipboardCheck size={30} /><h2>{status === "Available" ? "You are all caught up." : "Nothing here right now."}</h2><p>Completed tasks clear automatically. Scheduled tasks return when their next round opens.</p><button className="rw-button rw-button-secondary" onClick={() => { setStatus("All"); setCategory("All"); setSearch(""); }}>View all tasks</button></div>}
    <PromotionBanners placement="ad"/></div>
    {selectedId && !selected && <Modal title="Task details" onClose={() => setSelectedId(null)}><ResourceFeedback loading={detailLoading} error={error} initial retry={() => { const task = all.find(t => t.id === selectedId); if (task) void open(task); }} /></Modal>}
    {selected && <Modal title={selected.title} onClose={() => { if (!busy) setSelectedId(null); }}>
      {selected.taskType === "product_experience" && run?.status === "in_progress" ? <div className="rw-product-flow"><div className="rw-product-progress-head"><strong>{review ? "Review your answers" : `Product ${step + 1} of ${selected.products.length}`}</strong><span>{answered}/{selected.products.length}</span></div><div className="rw-product-progress"><i style={{ width: `${answered / selected.products.length * 100}%` }} /></div>
        {!review && product && <><article className="rw-product-card">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} /> : <div className="rw-product-placeholder"><Sparkles size={42} /></div>}<div><h2>{product.name}</h2><p>{product.description}</p></div></article><div className="rw-product-question">Do you know this product or have you used it before?</div><div className="rw-product-answers"><button onClick={() => answer(product.id, true)} className="rw-product-yes"><CheckCircle2 /><strong>Yes</strong><span>I know or have used {product.name}</span></button><button onClick={() => answer(product.id, false)} className="rw-product-no"><XCircle /><strong>No</strong><span>I have never used {product.name}</span></button></div><button className="rw-button rw-button-secondary" disabled={!step} onClick={() => setStep(step - 1)}><ArrowLeft size={16} />Previous</button></>}
        {review && <><div className="rw-product-review">{selected.products.map((item, index) => <button key={item.id} onClick={() => { setStep(index); setReview(false); }}><span>{item.name}</span><strong className={answers[item.id] ? "yes" : "no"}>{answers[item.id] ? "Yes" : "No"}</strong></button>)}</div>{error && <div className="form-error" role="alert">{error}</div>}<button className="rw-button rw-button-primary rw-full" disabled={busy || answered !== selected.products.length} onClick={completeProducts}>{busy ? "Adding your reward…" : `Complete task & earn ${points(run.rewardPoints)} points`}<Trophy size={17} /></button></>}
      </div> : <><span className="rw-tag">{selected.taskType === "survey" ? "SURVEY" : selected.taskType === "movie_review" ? "MOVIE REVIEW" : selected.taskType === "music_review" ? "MUSIC REVIEW" : selected.taskType === "image_preference" ? "IMAGE PREFERENCE POLL" : selected.taskType === "product_experience" ? "PRODUCT EXPERIENCE" : selected.category} · {run?.status === "approved" ? "READY TO CLAIM" : taskStatus({ ...selected, run: run || null })}</span><h2>{selected.title}</h2><TaskRepeatInfo hours={selected.repeatHours} nextAt={selected.nextAvailableAt} completed={run?.status === "completed"} /><p>{selected.description}</p>{["movie_review", "music_review"].includes(selected.taskType) && <div className="rw-media-content">{selected.products[0]?.imageUrl && <img className="rw-media-cover" src={selected.products[0].imageUrl} alt={selected.products[0].name} />}{selected.destinationUrl && <a className="rw-button rw-button-secondary" href={selected.destinationUrl} target="_blank" rel="noopener noreferrer">{selected.taskType === "movie_review" ? "Watch movie / clip" : "Listen to music"}<ArrowRight size={16} /></a>}<small>Opens in a new tab. Return here to submit your rating and review.</small></div>}<div className="rw-modal-reward"><span>Task reward</span><strong>+{points(run?.rewardPoints || selected.rewardPoints)} pts</strong></div><h3 className="rw-form-heading">{selected.taskType === "product_experience" ? "Have you used these products?" : "Your instructions"}</h3><p className="rw-proof-text">{selected.instructions}</p>{selected.taskType === "product_experience" && !run && <div className="rw-product-intro-stats"><span><strong>{selected.products.length}</strong> products</span><span><strong>2–3</strong> minutes</span><span><strong>Yes / No</strong> answers</span></div>}{error && <div className="form-error" role="alert">{error}</div>}{message && <div className="form-success" role="status">{message}</div>}
        {run?.status === "in_progress" && <p className="rw-draft-hint" role="status">Your unfinished answers are saved in this browser while you work.</p>}{run?.reviewReason && <div className="rw-notice"><p>Admin feedback: {run.reviewReason}</p></div>}{!run && <button className="rw-button rw-button-primary rw-full" disabled={busy || !selected.slotsRemaining} onClick={() => action("start")}>{busy ? "Starting…" : !selected.slotsRemaining ? "No slots remaining" : selected.taskType === "product_experience" ? "Start Product Experience" : "Start this task"}<ArrowRight size={16} /></button>}
        {run?.status === "in_progress" && run.verification === "survey" && <SurveyForm instant={run.autoClaimOnVerification} key={run.id} draftKey={draftKey(profile.user.id, run.id)} questions={selected.surveyQuestions || []} initialAnswers={run.surveyAnswers} busy={busy} onSubmit={surveyAnswers => { void action("submit", { surveyAnswers }); }} />}
        {run?.status === "in_progress" && run.verification === "rating_review" && <MediaReviewForm key={run.id} draftKey={draftKey(profile.user.id, run.id)} run={run} busy={busy} onSubmit={body => { void action("submit", body); }} />}
        {run?.status === "in_progress" && selected.taskType === "image_preference" && <form onSubmit={e => { e.preventDefault(); void completeProducts(); }} className="profile-form"><fieldset disabled={busy} className="rw-poll-form-fields"><legend>Which design do you prefer?</legend><p>Pick your favourite. Either choice earns the same reward.</p><div className="rw-poll-options">{selected.products.map((design, index) => <label key={design.id} className={"rw-poll-choice " + (selectedDesignId === design.id ? "is-selected" : "")}><input type="radio" name="preferred-design" value={design.id} checked={selectedDesignId === design.id} onChange={() => setSelectedDesignId(design.id)} required /><span className="rw-tag">Option {index === 0 ? "A" : "B"}</span>{design.imageUrl && <img src={design.imageUrl} alt={design.name} />}<strong>{design.name}</strong><span>{selectedDesignId === design.id ? "Selected" : "Choose this design"}</span></label>)}</div><button className="rw-button rw-button-primary rw-full" disabled={busy || !selectedDesignId}>{busy ? "Submitting?" : run.autoClaimOnApproval ? "Submit vote for approval" : "Submit vote & earn " + points(run.rewardPoints) + " points"}</button></fieldset></form>}
        {run?.status === "in_progress" && selected.taskType === "standard" && <form className="profile-form" onSubmit={e => { e.preventDefault(); void action("submit"); }}>{run.verification === "code" ? <label>Unique completion code<input value={code} onChange={e => setCode(e.target.value)} required /></label> : <label>Your feedback or proof<textarea value={proof} onChange={e => setProof(e.target.value)} required={!proofImage.startsWith("data:image/")} minLength={proofImage ? undefined : 10} maxLength={4000} rows={5} /></label>}{run.verification === "manual" && <label>Upload completion screenshot<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e => { const file = e.target.files?.[0]; if(file) { try { const uploaded = await imageData(file); setProofImage(uploaded); if (run) await saveDraftImage(draftKey(profile.user.id, run.id), uploaded); setError(""); } catch(error) { setError((error as Error).message); } } }} /><small>JPG, PNG or WebP, up to 2 MB.</small>{proofImage && <img className="rw-receipt-image" src={proofImage} alt="Task completion proof" />}</label>}<button className="rw-button rw-button-primary" disabled={busy}>Submit verification<ShieldCheck size={16} /></button></form>}{run?.status === "pending_review" && <div className="rw-notice"><p>{run.autoClaimOnApproval ? "Your submission is awaiting admin approval. Points will be added to your wallet automatically after approval." : "Your submission is awaiting review."}</p></div>}{run?.status === "approved" && <button className="rw-button rw-button-primary rw-full" disabled={busy} onClick={() => action("claim")}>Claim {points(run.rewardPoints)} points<Coins size={17} /></button>}{run?.status === "completed" && <div className="rw-notice"><CheckCircle2 /><p>{points(run.rewardPoints)} points were credited.</p><Link href="/wallet">View rewards</Link></div>}</>}
    </Modal>}
    {success && <Modal title="Task completed" onClose={() => setSuccess(null)} className="rw-success-modal"><div className="rw-confetti" aria-hidden="true">{Array.from({ length: 12 }, (_, index) => <i key={index} style={{ "--piece": index } as React.CSSProperties} />)}</div><div className="rw-success-icon"><Trophy size={45} /></div><span className="rw-tag">TASK COMPLETE</span><h2>{success.points ? `Congratulations, ${profile.user.name.split(" ")[0]}!` : "Already completed"}</h2><p>{success.title}</p><div className="rw-success-points"><Coins size={27} />+<AnimatedCounter value={success.points} /> <small>points</small></div><p>{success.points ? "Your reward is now safely in your wallet." : "This reward was already credited."}</p><div className="rw-inline-actions"><Link className="rw-button rw-button-primary" href="/wallet">View wallet<Trophy size={17} /></Link><button className="rw-button rw-button-secondary" onClick={() => setSuccess(null)}><Sparkles size={17} />Find another task</button></div></Modal>}
  </Shell>;
}
export default function Page() { return <AccountGate>{profile => <TaskPage profile={profile} />}</AccountGate>; }
