"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { ArrowDownToLine, ArrowRight, Bitcoin, Coins, CreditCard, History, Landmark, ShieldCheck } from "lucide-react";
import { AccountGate } from "../../components/account-gate";
import { Shell } from "../../components/shell";
import { AnimatedCounter, Modal } from "../../components/rewards/primitives";
import { Pagination, RefreshButton, ResourceFeedback, useResource } from "../../components/rewards/resource";
import { api, type Profile } from "../../lib/api";
import { date, money, points, paymentStatus, type Paged, type Transaction, type Wallet, type Withdrawal } from "../../lib/rewards";

function WalletPage({ profile }: { profile: Profile }) {
  const wallet = useResource<Wallet>("/wallet");
  const [ledgerPage, setLedgerPage] = useState(1); const [withdrawalPage, setWithdrawalPage] = useState(1);
  const ledger = useResource<Paged<Transaction>>(`/wallet/transactions?page=${ledgerPage}`);
  const withdrawals = useResource<Paged<Withdrawal>>(`/wallet/withdrawals?page=${withdrawalPage}`);
  const [tab, setTab] = useState("transactions");
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [amount, setAmount] = useState(""); const [provider, setProvider] = useState("paypal"); const [destination, setDestination] = useState("");
  const [source, setSource] = useState<"points" | "deposit">("points");
  const request = useRef<{ key: string; payload: string } | null>(null);
  const w = wallet.data;
  const amountCents = /^\d+(\.\d{1,2})?$/.test(amount) ? Number(amount.split(".")[0]) * 100 + Number((amount.split(".")[1] || "").padEnd(2, "0")) : 0;
  const availableCents = w ? (source === "points" ? w.withdrawableCents : w.withdrawableDepositCents) : 0;
  const cost = w && source === "points" ? Math.ceil(amountCents * w.rules.pointsPerUsd / 100) : 0;
  const canRequest = !!w && w.eligible && Math.max(w.withdrawableCents, w.withdrawableDepositCents) >= w.rules.minWithdrawalCents;
  async function refresh() { await Promise.all([wallet.refresh(), ledger.refresh(), withdrawals.refresh()]); }
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!w || busy) return; setBusy(true); setError("");
    try {
      if (!Number.isSafeInteger(amountCents) || !amountCents) throw new Error("Enter a USD amount with no more than two decimal places.");
      const payload = { amountCents, source, provider, destination: destination.trim() }; const fingerprint = JSON.stringify(payload);
      if (!request.current || request.current.payload !== fingerprint) request.current = { key: crypto.randomUUID(), payload: fingerprint };
      await api("/wallet/withdrawals", { method: "POST", body: JSON.stringify({ ...payload, requestKey: request.current.key }) });
      setOpen(false); setMessage(`Your ${money(amountCents)} withdrawal request was submitted. ${source === "points" ? `${points(cost)} points` : money(amountCents)} are reserved while it is reviewed.`); setTab("withdrawals"); setWithdrawalPage(1);
      await refresh();
    } catch (e) { setError((e as Error).message); }
    finally { setBusy(false); }
  }
  return <Shell name={profile.user.name} admin={profile.permissions.includes("users.read")}>
    <div className="page-heading"><div><span className="eyebrow">EVERY LITTLE WIN COUNTS</span><h1>Your rewards.</h1><p>Your verified earnings, available balance, and complete point history.</p></div><RefreshButton onClick={refresh} busy={wallet.loading || ledger.loading || withdrawals.loading} /></div>
    <ResourceFeedback {...wallet} retry={wallet.refresh} initial={!w} />
    {message && <div className="form-success" role="status">{message}</div>}
    {w && <><div className="rw-wallet-grid"><section className="rw-balance-card rw-live-balance rw-wallet-hero"><div className="rw-balance-top"><span>REWARDS AVAILABLE TO WITHDRAW</span><span className="rw-conversion-chip">{points(w.rules.pointsPerUsd)} pts = $1.00</span></div><div className="rw-earned"><AnimatedCounter value={w.withdrawableCents / 100} prefix="$" decimals={2} /></div><p className="rw-gold-points">{points(w.points)} reward points</p><div className="rw-cashout-label"><span>Minimum withdrawal {money(w.rules.minWithdrawalCents)}</span><strong>{Math.min(100, Math.floor(w.withdrawableCents / w.rules.minWithdrawalCents * 100))}%</strong></div><progress value={Math.min(w.withdrawableCents, w.rules.minWithdrawalCents)} max={w.rules.minWithdrawalCents} aria-label="Progress to minimum withdrawal" /><div className="rw-wallet-hero-actions"><Link href="/payments" className="rw-button rw-button-secondary"><CreditCard size={18} />Deposit</Link><button className="rw-button rw-button-primary rw-withdraw-button" disabled={!canRequest} onClick={() => { setSource(w.withdrawableCents >= w.rules.minWithdrawalCents ? "points" : "deposit"); setOpen(true); setError(""); setAmount((w.rules.minWithdrawalCents / 100).toFixed(2)); setDestination(""); request.current = null; }}><ArrowDownToLine size={18} />Withdraw</button></div></section><section className="panel rw-withdrawable"><span className="rw-panel-kicker">YOUR BALANCE, EXPLAINED</span><h2>Total rewards</h2><strong>{money(w.usdCents)}</strong><p>USD equivalent of all {points(w.points)} points. {points(w.reservedPoints)} points are reserved for pending or approved withdrawals.</p><span className={`rw-state-badge ${w.eligible ? "completed" : "pending_review"}`}>{w.eligible ? "Withdrawals enabled" : "Withdrawals on hold"}</span><small>{!w.eligible ? w.eligibilityReason || "Your account is not currently eligible to withdraw." : !canRequest ? `Earn ${money(Math.max(0, w.rules.minWithdrawalCents - w.withdrawableCents))} more to reach the minimum.` : `Minimum ${money(w.rules.minWithdrawalCents)} · Maximum ${money(w.rules.maxWithdrawalCents)}`}</small></section></div>
      <section className="panel rw-deposit-summary"><div><span className="rw-panel-kicker">DEPOSIT BALANCE · USD</span><h2>{money(w.depositCents)}</h2><p>{money(w.reservedDepositCents)} reserved for withdrawals · {money(w.withdrawableDepositCents)} available to withdraw.</p><small>Deposited funds are separate from your earned points.</small></div><Link href="/payments" className="rw-button rw-button-secondary">Add funds & view deposits<ArrowRight size={16} /></Link></section><div className="rw-module-stats rw-three-stats"><div className="panel"><span>Earned today (UTC)</span><strong>+{points(w.todayPoints)}<small> pts</small></strong></div><div className="panel"><span>Available points</span><strong>{points(w.points - w.reservedPoints)}</strong></div><div className="panel"><span>Withdrawal access</span><strong className="rw-stat-word">{w.eligible ? "Eligible" : "On hold"}</strong></div></div>
    </>}
    <section className="panel rw-payout-channels"><h2>Payout request methods</h2><div>{[[CreditCard, "PayPal"], [Landmark, "Bank transfer"], [Bitcoin, "Crypto"]].map(([Icon, label]) => { const PayoutIcon = Icon as typeof CreditCard; return <div key={String(label)}><span><PayoutIcon size={25} /></span><strong>{String(label)}</strong></div>; })}</div><p>Requests are reviewed by an admin. Payments are handled by the operator.</p></section>
    <section className="panel rw-history-panel"><div className="section-top"><div><span className="rw-panel-kicker">YOUR PAPER TRAIL</span><h2>Reward history</h2></div><History size={22} /></div><div className="rw-task-filters" role="group" aria-label="Reward history type"><button className={tab === "transactions" ? "is-active" : ""} aria-pressed={tab === "transactions"} onClick={() => setTab("transactions")}>Transactions</button><button className={tab === "withdrawals" ? "is-active" : ""} aria-pressed={tab === "withdrawals"} onClick={() => setTab("withdrawals")}>Withdrawals</button></div>
      {tab === "transactions" ? <><ResourceFeedback {...ledger} retry={ledger.refresh} initial={!ledger.data} />{ledger.data?.items.map(item => <div className="rw-history-row" key={item.id}><span className="rw-module-icon"><Coins size={20} /></span><div><strong>{item.description}</strong><small>{date(item.createdAt)}</small>{item.reservedPoints !== 0 && <small>{item.reservedPoints > 0 ? "Reserved" : "Reservation released"}: {points(Math.abs(item.reservedPoints))} pts</small>}</div><b className={item.points > 0 || item.depositCents > 0 ? "rw-positive" : ""}>{item.depositCents !== 0 ? `${item.depositCents > 0 ? "+" : ""}${money(item.depositCents)}` : item.reservedDepositCents !== 0 ? `${money(Math.abs(item.reservedDepositCents))} ${item.reservedDepositCents > 0 ? "reserved" : "released"}` : `${item.points > 0 ? "+" : ""}${points(item.points)} pts`}</b></div>)}{ledger.data?.total === 0 && <div className="rw-empty"><p>Your first claimed task will appear here.</p><Link href="/tasks" className="rw-button rw-button-secondary">Explore tasks<ArrowRight size={16} /></Link></div>}{ledger.data && <Pagination page={ledgerPage} total={ledger.data.total} onPage={setLedgerPage} busy={ledger.loading} />}</> : <><ResourceFeedback {...withdrawals} retry={withdrawals.refresh} initial={!withdrawals.data} />{withdrawals.data?.items.map(item => <article className="rw-withdrawal-row" key={item.id}><div><strong>{money(item.amountCents)}</strong><span className={`rw-state-badge ${item.status}`}>{paymentStatus(item.status)}</span></div><p>{item.provider.toUpperCase()} · {date(item.createdAt)}</p><small>{item.source === "deposit" ? "Deposit balance (USD)" : `${points(item.points)} points`} · {item.source === "points" ? `Rate at request: ${points(item.pointsPerUsd)} pts / USD` : "No points converted"}</small><details><summary>Request details</summary><p>{item.destination}</p><small>Reference: {item.id}</small>{item.reason && <p>Review: {item.reason}</p>}{item.paymentReference && <p>Payment reference: {item.paymentReference}</p>}</details></article>)}{withdrawals.data?.total === 0 && <div className="rw-empty"><p>No withdrawal requests yet. Your requests and review decisions will appear here.</p></div>}{withdrawals.data && <Pagination page={withdrawalPage} total={withdrawals.data.total} onPage={setWithdrawalPage} busy={withdrawals.loading} />}</>}
    </section>
    {open && w && <Modal title="Request withdrawal" onClose={() => { if (!busy) setOpen(false); }}><span className="rw-tag">YOUR NEXT REWARD</span><h2>Make a withdrawal.</h2><p>Available from selected balance: {money(availableCents)}. Requests are reviewed by an admin before payment.</p><form className="profile-form" onSubmit={submit}><label>Withdraw from<select value={source} onChange={e => setSource(e.target.value as "points" | "deposit")} disabled={busy}><option value="points">Earned rewards · {money(w.withdrawableCents)}</option><option value="deposit">Deposit balance · {money(w.withdrawableDepositCents)}</option></select></label><label>Amount in USD<input type="text" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} required maxLength={12} disabled={busy} /><small>Minimum {money(w.rules.minWithdrawalCents)} · Maximum {money(w.rules.maxWithdrawalCents)}</small></label><label>Payment method<select value={provider} onChange={e => { setProvider(e.target.value); setDestination(""); }} disabled={busy}><option value="paypal">PayPal</option><option value="crypto">Crypto</option><option value="bank">Bank transfer</option></select></label><label>{provider === "paypal" ? "PayPal email" : provider === "crypto" ? "Coin, network, and wallet address" : "Account holder, bank, and account / IBAN"}<textarea rows={3} value={destination} onChange={e => setDestination(e.target.value)} required minLength={provider === "paypal" ? 5 : 15} maxLength={300} disabled={busy} /><small>Check your details carefully. Never enter passwords, card security codes, or recovery phrases.</small></label><div className="rw-notice"><ShieldCheck size={20} /><p>{source === "points" ? `${points(cost)} points will be reserved at the current rate.` : `${money(amountCents)} will be reserved from your deposit balance.`} A rejected request releases the reservation. Payment is handled manually by the operator.</p></div>{error && <div className="form-error" role="alert">{error}</div>}<button className="rw-button rw-button-primary" disabled={busy || !w.eligible || amountCents < w.rules.minWithdrawalCents || amountCents > w.rules.maxWithdrawalCents || amountCents > availableCents || (source === "points" && cost > w.withdrawablePoints)}>{busy ? "Submitting…" : `Request ${money(amountCents)}`}<ArrowRight size={16} /></button></form></Modal>}
  </Shell>;
}
export default function Page() { return <AccountGate>{profile => <WalletPage profile={profile} />}</AccountGate>; }
