"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { ArrowDownToLine, ArrowRight, Bitcoin, Coins, CreditCard, History, ShieldCheck, WalletCards } from "lucide-react";
import { AccountGate } from "../../components/account-gate";
import { Shell } from "../../components/shell";
import { AnimatedCounter, Modal } from "../../components/rewards/primitives";
import { Pagination, RefreshButton, ResourceFeedback, useResource } from "../../components/rewards/resource";
import { api, type Profile } from "../../lib/api";
import { date, money, points, paymentStatus, type ReferralRequirement, type Paged, type Transaction, type Wallet, type PaymentMethod, type Withdrawal } from "../../lib/rewards";

function WalletPage({ profile }: { profile: Profile }) {
  const wallet = useResource<Wallet>("/wallet");
  const methods = useResource<PaymentMethod[]>("/payments/methods");
  const depositsEnabled = !!methods.data?.length;
  const [ledgerPage, setLedgerPage] = useState(1); const [withdrawalPage, setWithdrawalPage] = useState(1);
  const ledger = useResource<Paged<Transaction>>(`/wallet/transactions?page=${ledgerPage}`);
  const withdrawals = useResource<Paged<Withdrawal>>(`/wallet/withdrawals?page=${withdrawalPage}`);
  const [tab, setTab] = useState("transactions");
  const [referralPopup, setReferralPopup] = useState<ReferralRequirement | null>(null);
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [amount, setAmount] = useState(""); const [mobileNumber, setMobileNumber] = useState(""); const [destination, setDestination] = useState("");
  const request = useRef<{ key: string; payload: string } | null>(null);
  const w = wallet.data;
  const amountCents = /^\d+(\.\d{1,2})?$/.test(amount) ? Number(amount.split(".")[0]) * 100 + Number((amount.split(".")[1] || "").padEnd(2, "0")) : 0;
  const availableCents = w?.withdrawableCents || 0;
  const cost = w ? Math.ceil(amountCents * w.rules.pointsPerUsd / 100) : 0;
  const canRequest = !!w && w.eligible && w.withdrawableCents >= w.rules.minWithdrawalCents;
  const rewardShortfall = w ? Math.max(0, w.rules.minWithdrawalCents - w.withdrawableCents) : 0;
  async function refresh() { await Promise.all([wallet.refresh(), methods.refresh(), ledger.refresh(), withdrawals.refresh()]); }
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!w || busy) return; setBusy(true); setError("");
    try {
      const latest = await api<Wallet>("/wallet"); if (!latest.referralRequirement) throw new Error("Withdrawal eligibility could not be loaded. Please refresh and try again.");
      if (!latest.referralRequirement.met) { setOpen(false); setReferralPopup(latest.referralRequirement); await wallet.refresh(); return; }
      if (!Number.isSafeInteger(amountCents) || !amountCents) throw new Error("Enter a USD amount with no more than two decimal places.");
      const payload = { ...(mobileNumber.trim() ? { mobileNumber: mobileNumber.trim() } : {}), amountCents, source: "points", provider: "crypto", asset: "USDT", network: "TRON (TRC20)", address: destination.trim() }; const fingerprint = JSON.stringify(payload);
      if (!request.current || request.current.payload !== fingerprint) request.current = { key: crypto.randomUUID(), payload: fingerprint };
      await api("/wallet/withdrawals", { method: "POST", body: JSON.stringify({ ...payload, requestKey: request.current.key }) });
      setOpen(false); setMessage(`Your ${money(amountCents)} reward withdrawal was submitted. ${points(cost)} points are reserved while it is reviewed.`); setTab("withdrawals"); setWithdrawalPage(1);
      await refresh();
    } catch (e) { const detail = (e as Error & { details?: { code?: string; referralRequirement?: ReferralRequirement } }).details; if (detail?.code === "WITHDRAWAL_REFERRALS_REQUIRED" && detail.referralRequirement) { setOpen(false); setReferralPopup(detail.referralRequirement); } else setError((e as Error).message); }
    finally { setBusy(false); }
  }
  async function cancel(id: string) {
    setBusy(true); setError("");
    try { await api(`/wallet/withdrawals/${id}/cancel`, { method: "POST", body: "{}" }); setMessage("Withdrawal cancelled. Your reserved balance is available again."); await refresh(); }
    catch (e) { setError((e as Error).message); }
    finally { setBusy(false); }
  }
  return <Shell name={profile.user.name} admin={profile.permissions.includes("users.read")}>
    <div className="page-heading"><div><span className="eyebrow">EVERY LITTLE WIN COUNTS</span><h1>Your rewards.</h1><p>Your verified earnings, available balance, and complete point history.</p></div><RefreshButton onClick={refresh} busy={wallet.loading || ledger.loading || withdrawals.loading} /></div>
    <ResourceFeedback {...wallet} retry={wallet.refresh} initial={!w} />
    {message && <div className="form-success" role="status">{message}</div>}{error && !open && <div className="form-error" role="alert">{error}</div>}
    {w && <><div className="rw-wallet-grid"><section className="rw-balance-card rw-live-balance rw-wallet-hero"><div className="rw-balance-top"><span>REWARD BALANCE · WITHDRAWABLE</span><span className="rw-conversion-chip">{points(w.rules.pointsPerUsd)} pts = $1.00</span></div><div className="rw-earned"><AnimatedCounter value={w.withdrawableCents / 100} prefix="$" decimals={2} /></div><p className="rw-gold-points">{points(w.withdrawablePoints)} available reward points</p><div className="rw-cashout-label"><span>Minimum reward withdrawal {money(w.rules.minWithdrawalCents)}</span><strong>{Math.min(100, Math.floor(w.withdrawableCents / w.rules.minWithdrawalCents * 100))}%</strong></div><progress value={Math.min(w.withdrawableCents, w.rules.minWithdrawalCents)} max={w.rules.minWithdrawalCents} aria-label="Progress to minimum reward withdrawal" /><div className="rw-wallet-hero-actions">{depositsEnabled && <Link href="/payments" className="rw-button rw-button-secondary"><CreditCard size={18} />Deposit funds</Link>}{w.eligible && <button className="rw-button rw-button-primary rw-withdraw-button" disabled={!canRequest} onClick={() => { setOpen(true); setError(""); setAmount((w.rules.minWithdrawalCents / 100).toFixed(2)); setDestination(""); request.current = null; }}><ArrowDownToLine size={18} />Withdraw rewards</button>}</div></section><section className="panel rw-withdrawable rw-reward-detail-card"><div className="rw-reward-detail-icon"><Coins size={25} /></div><span className="rw-panel-kicker">TOTAL REWARD VALUE</span><h2>{points(w.points)} points</h2><strong>{money(w.usdCents)}</strong><p>Your task and referral rewards. {points(w.reservedPoints)} points are currently reserved for reward withdrawals.</p>{!w.eligible && <><span className="rw-state-badge pending_review">Withdrawals on hold</span><small>{w.eligibilityReason || "Your account is not currently eligible to withdraw."}</small></>}</section></div>
      <section className="panel rw-deposit-summary"><span className="rw-deposit-icon"><WalletCards size={27} /></span><div><span className="rw-panel-kicker">DEPOSIT BALANCE · MEMBERSHIP FUNDS</span><h2>{money(w.depositCents)}</h2><p>This balance pays for membership plans and stays separate from task rewards.</p><small>Deposits cannot be withdrawn. Only earned reward points can be withdrawn.</small><Link href="/payments#deposit-history" className="rw-deposit-history-link">View deposit status and history<ArrowRight size={14} /></Link></div>{depositsEnabled && <Link href="/payments" className="rw-button rw-button-primary">Deposit funds<ArrowRight size={16} /></Link>}</section><div className="rw-module-stats rw-three-stats rw-wallet-stats"><div className="panel"><span>Rewards earned today</span><strong>+{points(w.todayPoints)}<small> pts</small></strong></div><div className="panel"><span>Reward points available</span><strong>{points(w.points - w.reservedPoints)}</strong></div><div className="panel"><span>Reward withdrawal access</span><strong className="rw-stat-word">{!w.eligible ? "On hold" : !w.referralRequirement ? "Unavailable" : w.referralRequirement.met ? "Eligible" : "Referrals needed"}</strong></div></div>
    </>}
    {w && <section className="panel rw-wallet-next-step" aria-label="Withdrawal availability"><h2>Reward withdrawal status</h2>{!w.eligible ? <><p>{w.eligibilityReason || "Reward withdrawals are not available on this account right now."}</p>{!profile.user.emailVerified && <Link className="rw-button rw-button-secondary" href="/profile">Verify your email<ArrowRight size={16} /></Link>}</> : !w.referralRequirement.met ? <><p>You have {w.referralRequirement.qualified} of {w.referralRequirement.required} qualified referrals. Invite {w.referralRequirement.remaining} more to unlock reward withdrawals.</p><Link className="rw-button rw-button-secondary" href="/referrals">View referrals<ArrowRight size={16} /></Link></> : rewardShortfall > 0 ? <><p>Earn {money(rewardShortfall)} more in rewards to reach the {money(w.rules.minWithdrawalCents)} minimum.</p><Link className="rw-button rw-button-secondary" href="/tasks">Explore tasks<ArrowRight size={16} /></Link></> : <p>Your reward balance meets the minimum. You can request a USDT (TRC20) payout.</p>}</section>}
    {w?.eligible && <section className="panel rw-payout-channels"><h2>Payout request methods</h2><div>{[[Bitcoin, "USDT (TRC20)"]].map(([Icon, label]) => { const PayoutIcon = Icon as typeof CreditCard; return <div key={String(label)}><span><PayoutIcon size={25} /></span><strong>{String(label)}</strong></div>; })}</div><p>Requests are reviewed by an admin. Payments are handled by the operator.</p></section>}
    <section className="panel rw-history-panel"><div className="section-top"><div><span className="rw-panel-kicker">YOUR PAPER TRAIL</span><h2>Reward history</h2></div><History size={22} /></div><div className="rw-task-filters" role="group" aria-label="Reward history type"><button className={tab === "transactions" ? "is-active" : ""} aria-pressed={tab === "transactions"} onClick={() => setTab("transactions")}>Transactions</button><button className={tab === "withdrawals" ? "is-active" : ""} aria-pressed={tab === "withdrawals"} onClick={() => setTab("withdrawals")}>Withdrawals</button></div>
      {tab === "transactions" ? <><ResourceFeedback {...ledger} retry={ledger.refresh} initial={!ledger.data} />{ledger.data?.items.map(item => <div className="rw-history-row" key={item.id}><span className="rw-module-icon"><Coins size={20} /></span><div><strong>{item.description}</strong><small>{date(item.createdAt)}</small>{item.reservedPoints !== 0 && <small>{item.reservedPoints > 0 ? "Reserved" : "Reservation released"}: {points(Math.abs(item.reservedPoints))} pts</small>}</div><b className={item.points > 0 || item.depositCents > 0 ? "rw-positive" : ""}>{item.depositCents !== 0 ? `${item.depositCents > 0 ? "+" : ""}${money(item.depositCents)}` : item.reservedDepositCents !== 0 ? `${money(Math.abs(item.reservedDepositCents))} ${item.reservedDepositCents > 0 ? "reserved" : "released"}` : `${item.points > 0 ? "+" : ""}${points(item.points)} pts`}</b></div>)}{ledger.data?.total === 0 && <div className="rw-empty"><p>Your first claimed task will appear here.</p><Link href="/tasks" className="rw-button rw-button-secondary">Explore tasks<ArrowRight size={16} /></Link></div>}{ledger.data && <Pagination page={ledgerPage} total={ledger.data.total} onPage={setLedgerPage} busy={ledger.loading} />}</> : <><ResourceFeedback {...withdrawals} retry={withdrawals.refresh} initial={!withdrawals.data} />{withdrawals.data?.items.map(item => <article className="rw-withdrawal-row" key={item.id}><div><strong>{money(item.amountCents)}</strong><span className={`rw-state-badge ${item.status}`}>{paymentStatus(item.status)}</span></div><p>{item.provider.toUpperCase()} · {date(item.createdAt)}</p><small>{item.source === "deposit" ? "Deposit balance (USD)" : `${points(item.points)} points`} · {item.source === "points" ? `Rate at request: ${points(item.pointsPerUsd)} pts / USD` : "No points converted"}</small><details><summary>Request details</summary><p>{item.destination}</p>{item.mobileNumber && <p>Mobile: {item.mobileNumber}</p>}<small>Reference: {item.id}</small>{item.reason && <p>Review: {item.reason}</p>}{item.paymentReference && <p>Payment reference: {item.paymentReference}</p>}</details></article>)}{withdrawals.data?.total === 0 && <div className="rw-empty"><p>No withdrawal requests yet. Your requests and review decisions will appear here.</p></div>}{withdrawals.data && <Pagination page={withdrawalPage} total={withdrawals.data.total} onPage={setWithdrawalPage} busy={withdrawals.loading} />}</>}
    </section>
    {referralPopup && <Modal title="Referral requirement for withdrawal" onClose={() => { if (!busy) setReferralPopup(null); }}><span className="rw-tag">REWARD WITHDRAWAL REQUIREMENT</span><h2>{referralPopup.met ? "You are ready to withdraw" : "Invite friends to unlock withdrawals"}</h2><p>The current admin-set requirement is <strong>{referralPopup.required} qualified referrals</strong>.</p><div className="rw-modal-reward"><span>Your progress</span><strong>{referralPopup.qualified} / {referralPopup.required}</strong></div><progress aria-label="Qualified referral progress" value={Math.min(referralPopup.qualified, referralPopup.required)} max={referralPopup.required || 1} /><p>{referralPopup.remaining} more needed. A referral qualifies after verifying their email and completing the required tasks. Your reward points remain in your wallet; no withdrawal has been submitted.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="rw-inline-actions"><Link className="rw-button rw-button-primary" href="/referrals">Invite friends<ArrowRight size={16} /></Link><button className="rw-button rw-button-secondary" disabled={busy} onClick={async () => { setBusy(true); setError(""); try { const latest = await api<Wallet>("/wallet"); if (!latest.referralRequirement) throw new Error("Withdrawal eligibility could not be loaded. Please refresh and try again."); if (latest.referralRequirement.met) { setReferralPopup(null); setOpen(true); } else setReferralPopup(latest.referralRequirement); await wallet.refresh(); } catch (failure) { setError((failure as Error).message); } finally { setBusy(false); } }}>{busy ? "Checking..." : "Check progress"}</button></div></Modal>}
    {open && w?.eligible && <Modal title="Withdraw rewards" onClose={() => { if (!busy) setOpen(false); }}><span className="rw-tag">REWARD WITHDRAWAL</span><h2>Convert points to cash.</h2><div className="rw-modal-reward"><span>Available reward balance</span><strong>{money(availableCents)}</strong></div><p>{points(w.withdrawablePoints)} earned points are available. Deposit funds are separate and cannot be withdrawn.</p><form className="profile-form" onSubmit={submit}><label>Mobile number (optional)<input type="tel" autoComplete="tel" inputMode="tel" value={mobileNumber} onChange={e => setMobileNumber(e.target.value)} placeholder="+971 50 123 4567" maxLength={32} disabled={busy} /><small>Country code is optional. Used to contact you about this request.</small></label><label>Amount in USD<input type="text" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} required maxLength={12} disabled={busy} /><small>Minimum {money(w.rules.minWithdrawalCents)} · Maximum {money(w.rules.maxWithdrawalCents)} · Costs {points(cost)} points</small></label><div className="rw-form-columns"><label>Crypto<input value="USDT" readOnly /></label><label>Network<input value="TRC20" readOnly /></label></div><label>Wallet address<input type="text" value={destination} onChange={e => setDestination(e.target.value.trim())} required pattern="T[1-9A-HJ-NP-Za-km-z]{33}" minLength={34} maxLength={34} placeholder="Enter your TRC20 wallet address" autoComplete="off" spellCheck={false} disabled={busy} /><small>Use a USDT wallet address on the TRON (TRC20) network.</small></label><div className="rw-notice"><ShieldCheck size={20} /><p>{points(cost)} reward points will be reserved at the current rate. A rejected request releases them.</p></div>{error && <div className="form-error" role="alert">{error}</div>}<button className="rw-button rw-button-primary" disabled={busy || !w.eligible || amountCents < w.rules.minWithdrawalCents || amountCents > w.rules.maxWithdrawalCents || amountCents > availableCents || cost > w.withdrawablePoints}>{busy ? "Submitting…" : `Withdraw ${money(amountCents)}`}<ArrowRight size={16} /></button></form></Modal>}
    {tab === "withdrawals" && withdrawals.data?.items.some(item => item.status === "pending") && <section className="panel"><h2>Pending requests</h2><p>You can cancel a request until an administrator approves it.</p>{withdrawals.data.items.filter(item => item.status === "pending").map(item => <button key={item.id} className="rw-button rw-button-secondary" disabled={busy} onClick={() => void cancel(item.id)}>Cancel {money(item.amountCents)} request</button>)}</section>}
  </Shell>;
}
export default function Page() { return <AccountGate>{profile => <WalletPage profile={profile} />}</AccountGate>; }
