"use client";
import { useState } from "react";
import { BarChart3, BriefcaseBusiness, CircleDollarSign, ClipboardList, Plus, Sparkles, Target } from "lucide-react";
import { AccountGate } from "../../components/account-gate";
import { Shell } from "../../components/shell";
import { Modal } from "../../components/rewards/primitives";
import { RefreshButton, ResourceFeedback, useResource } from "../../components/rewards/resource";
import { api, type Profile } from "../../lib/api";
import { money, points } from "../../lib/rewards";

type Campaign = { id:string; name:string; objective:string; budgetCents:number; status:string; startsAt:string; endsAt:string|null; tasks:Array<{id:string;title:string;active:boolean;rewardPoints:number;completions:number;spentPoints:number}> };
type Overview = { campaigns:Campaign[]; totals:{campaigns:number;tasks:number;completions:number;spentPoints:number} };
type Template = { key:string;name:string;category:string;rewardPoints:number;description:string;instructions:string };

function AdvertiserPortal({profile}:{profile:Profile}) {
  const overview=useResource<Overview>("/advertiser/overview"); const templates=useResource<Template[]>("/advertiser/templates");
  const [campaignOpen,setCampaignOpen]=useState(false); const [briefFor,setBriefFor]=useState<Campaign|null>(null); const [selected,setSelected]=useState<Template|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  async function createCampaign(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const values=new FormData(form);setBusy(true);setError("");try{await api("/advertiser/campaigns",{method:"POST",body:JSON.stringify({name:values.get("name"),objective:values.get("objective"),budgetCents:Math.round(Number(values.get("budget"))*100),startsAt:new Date(String(values.get("startsAt"))+"Z").toISOString(),endsAt:values.get("endsAt")?new Date(String(values.get("endsAt"))+"Z").toISOString():null})});await overview.refresh();setCampaignOpen(false);setMessage("Campaign created as a draft.");}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function createBrief(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!briefFor)return;const form=event.currentTarget;const values=new FormData(form);setBusy(true);setError("");try{await api(`/advertiser/campaigns/${briefFor.id}/tasks`,{method:"POST",body:JSON.stringify({title:values.get("title"),description:values.get("description"),instructions:values.get("instructions"),category:values.get("category"),rewardPoints:Number(values.get("rewardPoints")),dailyLimit:Number(values.get("dailyLimit")),totalLimit:Number(values.get("totalLimit"))})});await overview.refresh();setBriefFor(null);setSelected(null);setMessage("Task brief sent for administrator review.");}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const totals=overview.data?.totals;
  const statCards: Array<{label:string;value:string|number;icon:typeof BriefcaseBusiness}> = totals ? [{label:"Campaigns",value:totals.campaigns,icon:BriefcaseBusiness},{label:"Task briefs",value:totals.tasks,icon:ClipboardList},{label:"Completions",value:totals.completions,icon:BarChart3},{label:"Reward spend",value:points(totals.spentPoints)+" pts",icon:CircleDollarSign}] : [];
  return <Shell name={profile.user.name}><div className="ad-advertiser-page"><div className="page-heading"><div><span className="eyebrow">ADVERTISER WORKSPACE</span><h1>Campaign center</h1><p>Plan research campaigns, submit task briefs, and monitor verified participation.</p></div><RefreshButton busy={overview.loading} onClick={overview.refresh}/></div>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}<ResourceFeedback {...overview} retry={overview.refresh} initial={!overview.data}/>
    {totals&&<div className="ad-advertiser-stats">{statCards.map(({label,value,icon:Icon})=><section className="panel" key={label}><Icon size={20}/><span>{label}<strong>{value}</strong></span></section>)}</div>}
    <section className="ad-advertiser-actions"><div><span className="rw-panel-kicker">CAMPAIGNS</span><h2>Your active workspace</h2></div><button className="rw-button rw-button-primary" onClick={()=>{setError("");setCampaignOpen(true)}}><Plus size={17}/>New campaign</button></section>
    <div className="ad-campaign-grid">{overview.data?.campaigns.map(campaign=><article className="panel ad-campaign-card" key={campaign.id}><div className="section-top"><span className="ad-campaign-icon"><Target size={21}/></span><span className={`rw-state-badge ${campaign.status==="active"?"completed":"pending_review"}`}>{campaign.status}</span></div><h2>{campaign.name}</h2><p>{campaign.objective}</p><div className="ad-campaign-budget"><span>Budget<strong>{money(campaign.budgetCents)}</strong></span><span>Tasks<strong>{campaign.tasks.length}</strong></span><span>Completions<strong>{campaign.tasks.reduce((sum,task)=>sum+task.completions,0)}</strong></span></div><div className="ad-campaign-tasks">{campaign.tasks.map(task=><div key={task.id}><span><strong>{task.title}</strong><small>{task.active?"Live":"Awaiting admin review"}</small></span><b>{task.completions}</b></div>)}{!campaign.tasks.length&&<p>No task briefs yet.</p>}</div><button className="rw-button rw-button-secondary rw-full" onClick={()=>{setError("");setSelected(null);setBriefFor(campaign)}}><Plus size={16}/>Add task brief</button></article>)}</div>
    {overview.data?.campaigns.length===0&&<section className="panel rw-empty"><BriefcaseBusiness size={30}/><h2>Create your first campaign</h2><p>Set a budget and objective, then add task briefs from reusable templates.</p><button className="rw-button rw-button-primary" onClick={()=>setCampaignOpen(true)}>Create campaign</button></section>}
    {campaignOpen&&<Modal title="New campaign" onClose={()=>!busy&&setCampaignOpen(false)}><h2>Plan a campaign</h2><form className="profile-form" onSubmit={createCampaign}><label>Campaign name<input name="name" minLength={3} maxLength={120} required/></label><label>Objective<textarea name="objective" minLength={10} maxLength={1000} required/></label><label>Budget (USD)<input name="budget" type="number" min="1" max="1000000" step="0.01" required/></label><div className="rw-form-columns"><label>Starts (UTC)<input name="startsAt" type="datetime-local" required/></label><label>Ends (UTC)<input name="endsAt" type="datetime-local"/></label></div><button className="rw-button rw-button-primary" disabled={busy}>{busy?"Creating…":"Create draft campaign"}</button></form></Modal>}
    {briefFor&&<Modal title="New task brief" onClose={()=>!busy&&setBriefFor(null)}><h2>{briefFor.name}</h2><p>Start from a template or enter a custom task. New briefs remain paused until an administrator reviews them.</p><ResourceFeedback {...templates} retry={templates.refresh} initial={!templates.data}/><div className="ad-template-picker">{templates.data?.map(template=><button type="button" className={selected?.key===template.key?"is-selected":""} key={template.key} onClick={()=>setSelected(template)}><Sparkles size={16}/><strong>{template.name}</strong><small>{points(template.rewardPoints)} pts suggested</small></button>)}</div><form className="profile-form" key={selected?.key||"custom"} onSubmit={createBrief}><label>Task title<input name="title" defaultValue={selected?.name||""} minLength={3} maxLength={120} required/></label><label>Description<textarea name="description" defaultValue={selected?.description||""} minLength={10} maxLength={500} required/></label><label>Instructions<textarea name="instructions" defaultValue={selected?.instructions||""} minLength={10} maxLength={4000} required/></label><label>Category<select name="category" defaultValue={selected?.category||"Feedback"}>{["Website","Video","App","Survey","Feedback","Other"].map(item=><option key={item}>{item}</option>)}</select></label><div className="rw-form-columns"><label>Reward points<input name="rewardPoints" type="number" defaultValue={selected?.rewardPoints||250} min={1} max={1000000} required/></label><label>Daily participants<input name="dailyLimit" type="number" defaultValue={100} min={1} required/></label><label>Total participants<input name="totalLimit" type="number" defaultValue={1000} min={1} required/></label></div><button className="rw-button rw-button-primary" disabled={busy}>{busy?"Submitting…":"Submit task brief"}</button></form></Modal>}
  </div></Shell>;
}

export default function Page(){return <AccountGate>{profile=>profile.permissions.includes("campaigns.manage")||profile.permissions.includes("rewards.manage")?<AdvertiserPortal profile={profile}/>:<Shell name={profile.user.name}><section className="panel rw-empty"><BriefcaseBusiness size={30}/><h1>Advertiser access required</h1><p>Ask an administrator to assign the Advertiser role to this account.</p></section></Shell>}</AccountGate>}
