/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { ArrowDownToLine, ArrowLeft, ArrowRight, CheckCircle2, Copy, CreditCard, Bitcoin, Receipt, ShieldCheck, ImagePlus } from "lucide-react";
import { AccountGate } from "../../components/account-gate";
import { Shell } from "../../components/shell";
import { Modal } from "../../components/rewards/primitives";
import { Pagination, RefreshButton, ResourceFeedback, useResource } from "../../components/rewards/resource";
import { api, type Profile } from "../../lib/api";
import { amountToCents, date, money, paymentStatus, type Deposit, type Paged, type PaymentMethod, type Wallet } from "../../lib/rewards";
import { imageData } from "../../lib/image-upload";

function MobileMoneyInstructions({ method }: { method: PaymentMethod }) {
  return <div className="rw-payment-instructions" aria-label="Mobile Money payment instructions">
    <h3>Mobile Money payment instructions</h3>
    <p>Send to the receiving number below using <strong>{method.network}</strong>. Check the number and operator before paying.</p>
    <p><strong>Receiving number</strong></p>
    <p className="rw-proof-text rw-selectable">{method.recipient}</p>
    <p className="rw-proof-text">{method.instructions}</p>
    <small>Create a deposit request before sending money so you have a request ID to include with your receipt.</small>
  </div>;
}

function DepositDetails({ deposit: initial, onClose }: { deposit: Deposit; onClose: () => void }) {
  const [deposit, setDeposit] = useState(initial);
  const [reference, setReference] = useState(initial.paymentReference || "");
  const [proofImage, setProofImage] = useState(initial.proofImage || "");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [cancel, setCancel] = useState(false);
  const isCrypto = deposit.provider === "crypto"; const isBank = deposit.provider === "bank";
  const editable = ["awaiting_payment", "rejected"].includes(deposit.status);
  async function submit(e: React.FormEvent) {
    e.preventDefault(); if (busy) return; setBusy(true); setError("");
    try { setDeposit(await api<Deposit>(`/payments/deposits/${deposit.id}/proof`, { method: "POST", body: JSON.stringify({ ...(deposit.asset === "USDT" ? {} : { paymentReference: reference }), ...(proofImage ? { proofImage } : {}) }) })); setMessage("Proof submitted. Your balance updates after the payment is confirmed by an admin."); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); setMessage("Copied."); } catch { setError("Select the details below and copy them manually."); } }
  return <Modal title="Deposit details" onClose={() => { if (!busy) onClose(); }}><span className={`rw-state-badge ${deposit.status}`}>{paymentStatus(deposit.status)}</span><h2>{money(deposit.amountCents)} deposit</h2><p>{deposit.methodLabel} · Created {date(deposit.createdAt)}</p><ol className="rw-payment-steps"><li className="is-done">1. Request created</li><li className={deposit.paymentReference ? "is-done" : ""}>2. Send payment & proof</li><li className={deposit.status === "completed" ? "is-done" : ""}>3. Admin confirms funds</li></ol>
    {editable && <><div className="rw-payment-instructions"><div className="section-top"><h3>{isCrypto ? "Crypto receiving details" : isBank ? "Bank transfer details" : "Mobile Money receiving number"}</h3><button className="rw-icon-button" aria-label="Copy payment recipient" onClick={() => copy(deposit.recipient)}><Copy size={18} /></button></div><p>{isCrypto ? "Requested credit: " : "Transfer amount: "}<strong>{money(deposit.amountCents)} USD</strong>. {isCrypto ? "Use the coin, network, and amount calculation specified by the operator below." : "Use the receiving account and currency specified below."}</p><p className="rw-proof-text rw-selectable">{deposit.recipient}</p>{deposit.provider === "mobile_money" && <p>Operator: {deposit.network}</p>}{deposit.asset && <div className="rw-crypto-quote"><strong>Send {deposit.cryptoAmount} {deposit.asset}</strong><p>Network: <b>{deposit.network}</b></p><small>Quoted credit: {money(deposit.amountCents)} · Operator rate: 1 {deposit.asset} = {money(deposit.usdRateCents || 0)}</small><button type="button" className="rw-button rw-button-secondary" onClick={() => copy(deposit.cryptoAmount || "")}>Copy amount</button><p>Use this exact asset and network. Allow for fees so the receiving wallet gets the quoted amount.</p></div>}<p className="rw-proof-text">{deposit.instructions}</p></div><div className="rw-payment-reference"><small>Your deposit request ID</small><code>{deposit.id}</code><button className="rw-button rw-button-secondary" onClick={() => copy(deposit.id)}><Copy size={15} />Copy request ID</button></div><div className="rw-notice"><p>{deposit.status === "rejected" ? "If you already paid, do not pay again. Read the reviewer’s feedback and resubmit proof for the original payment." : "Include your request ID in the transfer note when supported. Send payment only once. A request alone does not credit your wallet."}</p></div></>}
    {!editable && deposit.asset && <div className="rw-payment-instructions"><strong>{deposit.cryptoAmount} {deposit.asset} · {deposit.network}</strong><p className="rw-proof-text rw-selectable">{deposit.recipient}</p><p>Transaction: {deposit.paymentReference || "Not submitted"}</p></div>}{deposit.reviewReason && <div className="rw-notice"><strong>Review feedback</strong><p>{deposit.reviewReason}</p></div>}{error && <div className="form-error" role="alert">{error}</div>}{message && <div className="form-success" role="status">{message}</div>}
    {deposit.mobileNumber && <p>Mobile: {deposit.mobileNumber}</p>}{editable && <form className="profile-form" onSubmit={submit}>{deposit.asset !== "USDT" && <label>{isCrypto ? "Transaction hash (TXID)" : isBank ? "Bank transfer reference" : "Provider transaction reference"}<input value={reference} onChange={e => setReference(e.target.value)} required minLength={5} maxLength={160} readOnly={!!deposit.paymentReference} disabled={busy} placeholder={isCrypto ? "Paste the transaction hash from your wallet" : "Reference from your payment receipt"} /></label>}<label className="rw-image-upload"><ImagePlus size={24} /><span><strong>Upload payment receipt</strong><small>JPG, PNG, or WebP · maximum 2 MB</small></span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { setProofImage(await imageData(file)); setError(""); } catch (failure) { setError((failure as Error).message); e.target.value = ""; } }} /></label>{proofImage && <div className="rw-upload-preview"><img src={proofImage} alt="Payment receipt preview" /><button type="button" className="rw-button rw-button-secondary" onClick={() => setProofImage("")}>Remove image</button></div>}<label className="rw-check-field"><input type="checkbox" required disabled={busy} />I have already sent this payment.</label><button className="rw-button rw-button-primary" disabled={busy}>{busy ? "Submitting…" : "Submit payment for review"}<ShieldCheck size={17} /></button></form>}
    {deposit.status === "pending_review" && <div className="rw-notice"><ShieldCheck size={24} /><p>Your payment is under review. No funds have been credited yet. Close this dialog to follow the status in your deposit history.</p></div>}
    {deposit.status === "completed" && <div className="rw-notice"><CheckCircle2 size={24} /><p>{money(deposit.amountCents)} was credited to your deposit balance. Earned points were not changed.</p></div>}
    {deposit.status === "awaiting_payment" && <div className="rw-cancel-deposit">{!cancel ? <button className="rw-button rw-button-secondary" disabled={busy} onClick={() => setCancel(true)}>Cancel unpaid request</button> : <><p>Only cancel if you have not sent money. Already paid? Submit the proof instead.</p><div className="rw-inline-actions"><button className="rw-button rw-button-secondary" disabled={busy} onClick={async () => { setBusy(true); setError(""); try { setDeposit(await api<Deposit>(`/payments/deposits/${deposit.id}/cancel`, { method: "POST", body: "{}" })); setMessage("Unpaid request cancelled."); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>I have not paid · Cancel</button><button className="rw-button rw-button-secondary" disabled={busy} onClick={() => setCancel(false)}>Keep request</button></div></>}</div>}
  </Modal>;
}

function PaymentsPage({ profile }: { profile: Profile }) {
  const wallet = useResource<Wallet>("/wallet"); const methods = useResource<PaymentMethod[]>("/payments/methods");
  const [page, setPage] = useState(1); const history = useResource<Paged<Deposit> & { totalDepositedCents: number }>(`/payments/deposits?page=${page}`);
  const [selectedAsset, setAsset] = useState("USDT");
  const [selectedProvider, setProvider] = useState("crypto"); const [amount, setAmount] = useState(""); const [mobileNumber, setMobileNumber] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState<Deposit | null>(null);
  const requestKey = useRef<{ key: string; payload: string } | null>(null);
  const available = methods.data || [];
  const coins = ["USDT", "BTC", "ETH"].filter(coin => available.some(m => m.provider === "crypto_" + coin.toLowerCase()));
  const providers = [["crypto", "Crypto"], ["mobile_money", "Mobile Money"]].filter(([key]) => key === "crypto" ? coins.length > 0 : available.some(m => m.provider === key));
  const provider = providers.some(([key]) => key === selectedProvider) ? selectedProvider : providers[0]?.[0];
  const asset = coins.includes(selectedAsset) ? selectedAsset : coins[0];
  const method = methods.data?.find(m => m.provider === (provider === "crypto" ? `crypto_${(asset || "").toLowerCase()}` : provider)); const cents = amountToCents(amount);
  async function refresh() { await Promise.all([wallet.refresh(), history.refresh(), methods.refresh()]); }
  async function create(e: React.FormEvent) {
    e.preventDefault(); if (busy || !method) return; setBusy(true); setError("");
    try {
      const payload = { ...(mobileNumber.trim() ? { mobileNumber: mobileNumber.trim() } : {}), provider, ...(provider === "crypto" ? { asset } : {}), amountCents: cents }; const fingerprint = JSON.stringify(payload);
      if (!requestKey.current || requestKey.current.payload !== fingerprint) requestKey.current = { key: crypto.randomUUID(), payload: fingerprint };
      const deposit = await api<Deposit>("/payments/deposits", { method: "POST", body: JSON.stringify({ ...payload, requestKey: requestKey.current.key }) });
      setSelected(deposit); setAmount(""); requestKey.current = null; setPage(1); await refresh();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <Shell name={profile.user.name} admin={profile.permissions.includes("users.read")}><Link href="/wallet" className="rw-button rw-button-secondary"><ArrowLeft size={15} />Back to wallet</Link><div className="page-heading"><div><span className="eyebrow">CLEAR STEPS. TRACKED PAYMENTS.</span><h1>Add money to your wallet.</h1><p>Choose an available payment method below. Follow your payment from request to confirmation.</p></div><RefreshButton onClick={refresh} busy={wallet.loading || methods.loading || history.loading} /></div>
    <ResourceFeedback {...wallet} retry={wallet.refresh} initial={!wallet.data} />{wallet.data && <div className="rw-balance-separation"><section className="panel rw-deposit-funds-card"><span>DEPOSIT BALANCE · MEMBERSHIP FUNDS</span><strong>{money(wallet.data.depositCents)}</strong><p>Use this balance for membership purchases. Deposits are separate from rewards and cannot be withdrawn.</p></section><section className="panel rw-reward-funds-card"><span>REWARD BALANCE · WITHDRAWABLE</span><strong>{money(wallet.data.withdrawableCents)}</strong><p>{wallet.data.withdrawablePoints.toLocaleString()} task and referral points available for reward withdrawal.</p></section></div>}
    {available.length > 0 && <section className="rw-crypto-only-banner"><span className="rw-module-icon"><Bitcoin size={28} /></span><div><strong>Deposit methods</strong><p>Follow the instructions for your selected payment method.</p></div><span className="rw-state-badge completed"><CheckCircle2 size={14} />Available</span></section>}
    <div className="rw-payment-layout"><section className="panel"><div className="section-top"><h2>Make a deposit</h2><CreditCard size={22} /></div><ol className="rw-payment-steps"><li>1. Choose method & amount</li><li>2. Send payment & submit proof</li><li>3. Admin confirms your balance</li></ol><ResourceFeedback {...methods} retry={methods.refresh} initial={!methods.data} /><div className="rw-task-filters" role="group" aria-label="Deposit method">{providers.map(([key,label]) => <button type="button" key={key} className={provider === key ? "is-active" : ""} aria-pressed={provider === key} disabled={busy} onClick={() => {setProvider(key); setError(""); requestKey.current=null;}}>{label}</button>)}</div>{provider === "crypto" && <div className="rw-task-filters" role="group" aria-label="Choose cryptocurrency">{coins.map(coin => <button type="button" key={coin} aria-pressed={asset === coin} className={asset === coin ? "is-active" : ""} disabled={busy} onClick={() => { setAsset(coin); setError(""); requestKey.current = null; }}>{coin}</button>)}</div>}{methods.data && !method && <div className="rw-notice"><p>{"No deposit methods are currently available."}</p>{profile.permissions.includes("rewards.manage") && <Link href="/admin/payments" className="rw-button rw-button-primary">Set up payment methods</Link>}</div>}
    {method && <form className="profile-form" onSubmit={create}><div className="rw-deposit-context"><strong>{method.label}{provider === "crypto" ? ` · ${method.network}` : ""}</strong>{provider === "crypto" && <p>Operator rate: 1 {asset} = {money(method.usdRateCents)} USD. Your exact amount and receiving address appear after creating the request.</p>}<p>{provider === "crypto" ? asset === "USDT" ? "Create your request, send the exact USDT amount, then upload a clear payment receipt. No transaction ID is required." : "Create your request to see the receiving wallet and network instructions. Submit the transaction hash after sending." : "The receiving number and operator are in the instructions below. Create a request ID before paying, then upload your receipt."}</p></div>{provider === "mobile_money" && <MobileMoneyInstructions method={method} />}<label>Your mobile number (optional)<input type="tel" autoComplete="tel" inputMode="tel" value={mobileNumber} onChange={e => setMobileNumber(e.target.value)} placeholder="+971 50 123 4567" maxLength={32} disabled={busy} /><small>Country code is optional. Used to contact you about this request.</small></label><label>Amount (USD)<input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" required maxLength={12} disabled={busy} /><small>Minimum {money(method.minimumCents)} · Maximum {money(method.maximumCents)}</small></label><div className="rw-notice"><p>{provider === "mobile_money" ? "Review the receiving details above, then create your deposit request before sending money." : "Create a deposit request to get the exact crypto payment details before sending money."} Only a confirmed payment credits your deposit balance.</p></div>{error && <div className="form-error" role="alert">{error}</div>}<button className="rw-button rw-button-primary" disabled={busy || cents < method.minimumCents || cents > method.maximumCents}>{busy ? "Creating request…" : "Create deposit request"}<ArrowRight size={17} /></button></form>}</section>
    <section className="panel rw-payment-explainer"><h2>How your money is tracked</h2><div><span className="rw-module-icon"><Receipt size={23} /></span><p><strong>Deposit balance</strong> is confirmed money added for membership purchases. It cannot be withdrawn.</p></div><div><span className="rw-module-icon"><ShieldCheck size={23} /></span><p><strong>Under review</strong> means the operator is checking your uploaded receipt. Submission does not credit funds until approval.</p></div><div><span className="rw-module-icon"><ArrowDownToLine size={23} /></span><p><strong>Reward balance</strong> contains task and referral earnings. Only this balance can be withdrawn.</p></div><Link href="/wallet" className="rw-button rw-button-secondary">View separate balances<ArrowRight size={16} /></Link></section></div>
    <section id="deposit-history" className="rw-history-panel"><div className="section-top"><h2>Deposit history {history.data ? `(${history.data.total})` : ""}</h2>{history.data && <span className="rw-reward-pill">Confirmed {money(history.data.totalDepositedCents)}</span>}</div><ResourceFeedback {...history} retry={history.refresh} initial={!history.data} />{history.data?.items.map(deposit => <article className="rw-withdrawal-row" key={deposit.id}><div><strong>{money(deposit.amountCents)}</strong><span className={`rw-state-badge ${deposit.status}`}>{paymentStatus(deposit.status)}</span></div><p>{deposit.methodLabel} · {date(deposit.createdAt)}</p><small className="rw-selectable">Request {deposit.id}</small><div className="rw-inline-actions"><button className="rw-button rw-button-secondary" onClick={() => { setSelected(deposit); setError(""); }}>{deposit.status === "awaiting_payment" ? "Instructions & submit proof" : deposit.status === "rejected" ? "Feedback & resubmit" : "View details"}</button></div></article>)}{history.data?.total === 0 && <div className="panel rw-empty"><Receipt size={30} /><h3>Your payment history starts here.</h3><p>Every deposit request and its review status will appear in this list.</p></div>}{history.data && <Pagination page={page} total={history.data.total} onPage={setPage} busy={history.loading} />}</section>
    {selected && <DepositDetails key={selected.id} deposit={selected} onClose={() => { setSelected(null); void refresh(); }} />}
  </Shell>;
}
export default function Page() { return <AccountGate>{profile => <PaymentsPage profile={profile} />}</AccountGate>; }
