"use client";
import Link from "next/link";
import { ArrowDownLeft, ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, Clock3, Coins, Crown, Globe2, Layers2, Play, ShieldCheck, Sparkles, Users, Wallet } from "lucide-react";
import { Shell } from "./shell";
import type { Profile } from "../lib/api";
const sampleTasks = [
  { title: "Discover something new", text: "Explore a featured website", category: "Explore", icon: Globe2, color: "peach", points: 120, time: "2 min" },
  { title: "A fresh perspective", text: "Watch an approved brand story", category: "Watch", icon: Play, color: "lavender", points: 200, time: "5 min" },
  { title: "Your opinion matters", text: "Share thoughtful product feedback", category: "Feedback", icon: Users, color: "mint", points: 350, time: "8 min" },
];
export function Dashboard({ profile }: { profile?: Profile }) {
  const preview = !profile;
  return <Shell preview={preview} name={profile?.user.name} admin={profile?.permissions.includes("users.read")}>
    <div className="page-heading"><div><div className="eyebrow">YOUR DAILY DOSE OF POSSIBILITY</div><h1>{preview ? "A little effort. A little more." : `Welcome, ${profile.user.name.split(" ")[0]}.`}</h1><p>Turn a few spare moments into something rewarding.</p></div><span className="date-chip"><span className="sun-icon">✳</span> One task at a time</span></div>
    {preview ? <div className="preview-note"><span><Sparkles size={16} /><strong>Take a look around.</strong> Sample data previews upcoming rewards features.</span><Link href="/register">Create your account <ArrowRight size={16} /></Link></div> : <div className="preview-note"><span><ShieldCheck size={17} /><strong>Your account is ready.</strong> Tasks and wallet services arrive in the next modules.</span><Link href="/profile">View profile <ArrowRight size={16} /></Link></div>}
    <section className="stats-grid" aria-label="Balance summary">
      <article className="stat-card featured"><div className="stat-label">Total points <Coins size={19} /></div><div className="stat-value">{preview ? "12,450" : "—"}<span>pts</span></div><div className="stat-foot">{preview ? <><span className="tiny-pill">↗ 12.8%</span> sample monthly growth</> : "Points ledger coming next"}</div></article>
      <article className="stat-card"><div className="stat-label">USD equivalent <span className="currency-icon">$</span></div><div className="stat-value">{preview ? "$124.50" : "—"}</div><div className="stat-foot">{preview ? "Illustrative rate · 100 points = $1" : "Conversion rate not configured"}</div></article>
      <article className="stat-card"><div className="stat-label">Withdrawable <Wallet size={19} /></div><div className="stat-value">{preview ? "$85.00" : "—"}<span className="available-dot" /></div><div className="stat-foot">{preview ? "Sample eligible balance" : "Withdrawals not enabled yet"}</div></article>
      <article className="stat-card"><div className="stat-label">Today’s earnings <Sparkles size={19} /></div><div className="stat-value">{preview ? "+450" : "—"}<span>pts</span></div><div className="stat-foot">{preview ? <><CheckCircle2 size={14} /> 3 sample tasks completed</> : "Your journey starts here"}</div></article>
    </section>
    <div className="dashboard-columns"><div className="dashboard-primary">
      <section className="hero-card"><div className="hero-copy"><span className="hero-kicker"><span /> MAKE YOUR TIME COUNT</span><h2>Your next reward<br />starts with a small step.</h2><p>Find a task that fits your day.<br />Complete it. Get verified. Earn points.</p><Link className="button dark" href={preview ? "/register" : "/tasks"}>{preview ? "Start your journey" : "Explore tasks"}<ArrowUpRight size={17} /></Link></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="floating-check"><Check size={22} /></div><div className="reward-token"><Layers2 size={58} strokeWidth={1.8} /></div><div className="floating-spark">✳</div><div className="reward-ticket"><span className="ticket-icon"><CheckCircle2 size={23} /></span><span>Little wins add up<strong>Keep moving forward</strong></span></div></div></section>
      <section className="panel earnings-panel"><div className="section-top"><div><h2>Earnings overview</h2><p>{preview ? "Your progress, one day at a time" : "Your earnings will appear when rewards launch"}</p></div><span className="select-chip">Last 7 days</span></div><div className="chart-key"><span className="orange-dot" /><span>Points earned</span>{preview && <strong>2,850 <small>pts this week · sample</small></strong>}</div><div className="chart" role="img" aria-label={preview ? "Sample points earned: Monday 350, Tuesday 500, Wednesday 280, Thursday 620, Friday 400, Saturday 250, Sunday 450" : "No earnings data yet"}><div className="chart-y"><span>800</span><span>600</span><span>400</span><span>200</span><span>0</span></div><div className="chart-bars">{[350, 500, 280, 620, 400, 250, 450].map((v, i) => <div className="bar-col" key={i}><div className={`bar ${i === 6 ? "current" : ""}`} style={{ height: preview ? `${v / 8}%` : "2px" }}>{preview && i === 6 && <span className="bar-tooltip">450 pts</span>}</div><span>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][i]}</span></div>)}</div></div></section>
      <section><div className="section-top tasks-title"><div><h2>A little something for everyone</h2><p>{preview ? "A preview of the kinds of tasks you’ll find" : "Task categories planned for the next module"}</p></div><Link href="/tasks" className="text-link">Explore <ArrowRight size={16} /></Link></div><div className="task-grid">{sampleTasks.map(({ title, text, category, icon: Icon, color, points, time }) => <article className="task-card" key={title}><div className="task-card-top"><span className={`task-icon ${color}`}><Icon size={22} /></span><span className="task-category">{category}</span></div><h3>{title}</h3><p>{text}</p><div className="task-meta"><span><Clock3 size={13} />{time}</span><span>{preview ? "Sample task" : "Coming soon"}</span></div><div className="task-reward"><strong>{preview ? `+${points}` : "—"} <small>pts</small></strong><Link href="/tasks" aria-label={`Learn about ${category.toLowerCase()} tasks`}><ArrowUpRight size={18} /></Link></div></article>)}</div></section>
    </div><aside className="dashboard-secondary">
      <section className="panel progress-panel"><div className="section-top"><h2>Daily momentum</h2><span className="soft-icon"><Sparkles size={18} /></span></div><div className="progress-ring" style={{ "--progress": preview ? "60%" : "0%" } as React.CSSProperties}><div><strong>{preview ? "3" : "0"}<span> / {preview ? "5" : "0"}</span></strong><small>{preview ? "sample tasks" : "available tasks"}</small></div></div><h3>{preview ? "You’re finding your rhythm" : "A fresh start awaits"}</h3><p>{preview ? "Small wins make a big difference.\nKeep the good momentum going." : "Progress appears here when\napproved tasks become available."}</p><div className="progress-bottom"><span><span className="orange-dot" />Daily progress</span><strong>{preview ? "60%" : "—"}</strong></div></section>
      <section className="membership-card"><span className="membership-label"><Crown size={18} /> MEMBERSHIP</span><h2>Room to grow.</h2><p>More possibilities, at your pace.<br />Explore the benefits of membership.</p><div className="membership-divider" /><Link href="/membership">Discover memberships <ArrowUpRight size={17} /></Link></section>
      <section className="panel activity-panel"><div className="section-top"><h2>Recent activity</h2><span className="soft-icon"><Clock3 size={17} /></span></div>{preview ? <>{[{ text: "Website task approved", sub: "Today, 10:42 AM", value: "+120 pts" }, { text: "Feedback approved", sub: "Today, 9:18 AM", value: "+250 pts" }, { text: "Referral qualified", sub: "Yesterday", value: "+500 pts" }].map(a => <div className="activity-item" key={a.text}><span className="activity-icon"><ArrowDownLeft size={17} /></span><div><strong>{a.text}</strong><small>{a.sub}</small></div><b>{a.value}</b></div>)}<span className="sample-caption">Illustrative activity · no real transactions</span></> : <div className="empty-activity"><ShieldCheck size={24} /><strong>Email verified</strong><p>Your account is ready for the next step.</p></div>}<Link className="panel-footer-link" href={preview ? "/register" : "/profile"}>{preview ? "Begin your own story" : "Manage your account"}<ChevronRight size={15} /></Link></section>
    </aside></div>
  </Shell>;
}
