"use client";
import { useEffect, useState } from "react";
import { Check, Globe2, X } from "lucide-react";
import { api, type Profile } from "../lib/api";
const regions = [["AE","United Arab Emirates","AED","ar"],["GH","Ghana","GHS","en"],["NG","Nigeria","NGN","en"],["US","United States","USD","en"],["GB","United Kingdom","GBP","en"],["CA","Canada","CAD","en"],["FR","France","EUR","fr"],["DE","Germany","EUR","en"],["ZA","South Africa","ZAR","en"],["KE","Kenya","KES","en"],["IN","India","INR","en"],["PK","Pakistan","PKR","en"],["PH","Philippines","PHP","en"],["SG","Singapore","SGD","en"],["SA","Saudi Arabia","SAR","ar"],["QA","Qatar","QAR","ar"],["KW","Kuwait","KWD","ar"],["BH","Bahrain","BHD","ar"],["OM","Oman","OMR","ar"],["EG","Egypt","EGP","ar"],["AU","Australia","AUD","en"],["JP","Japan","JPY","en"],["CN","China","CNY","en"],["BR","Brazil","BRL","en"],["MX","Mexico","MXN","en"]] as const;
const languages = [["en","English"],["fr","Français"],["ar","العربية"]] as const;
export function RegionToggle() {
 const [open,setOpen]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[country,setCountry]=useState(""),[language,setLanguage]=useState("en"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{api<Profile>("/me").then(value=>{setProfile(value);setCountry(value.user.countryCode||"");setLanguage(value.user.languageCode||"en");document.documentElement.lang=value.user.languageCode||"en";document.documentElement.dir=value.user.languageCode==="ar"?"rtl":"ltr";}).catch(()=>undefined)},[]);
 const region=regions.find(([code])=>code===country);
 async function save(){if(!profile||!country)return;setBusy(true);setError("");try{await api("/me",{method:"PATCH",body:JSON.stringify({name:profile.user.name,countryCode:country,currencyCode:null,languageCode:language})});window.location.reload()}catch(failure){setError((failure as Error).message);setBusy(false)}}
 return <div className="rw-region-control"><button type="button" className="rw-icon-button rw-region-toggle" aria-label="Change region, currency and language" aria-expanded={open} onClick={()=>setOpen(!open)}><Globe2 size={19}/><small>{country||"Region"}</small></button>{open&&<><button className="rw-region-backdrop" aria-label="Close region settings" onClick={()=>setOpen(false)}/><section className="rw-region-popover" role="dialog" aria-modal="true" aria-label="Region settings"><header><div><span>REGION SETTINGS</span><h2>Make Rewardly local</h2></div><button className="rw-icon-button" aria-label="Close" onClick={()=>setOpen(false)}><X size={18}/></button></header><p>Choose your location and language. Your display currency updates automatically.</p><label>Country or region<select value={country} onChange={event=>{const value=event.target.value;setCountry(value);const selected=regions.find(([code])=>code===value);if(selected)setLanguage(selected[3])}}><option value="" disabled>Select a region</option>{regions.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><div className="rw-region-summary"><Globe2 size={18}/><span><small>Display currency</small><strong>{region?.[2]||"—"}</strong></span><Check size={17}/></div><label>Language<select value={language} onChange={event=>setLanguage(event.target.value)}>{languages.map(([code,name])=><option value={code} key={code}>{name}</option>)}</select></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="rw-button rw-button-primary" disabled={busy||!country||!profile} onClick={save}>{busy?"Applying…":"Apply settings"}</button><small className="rw-region-footnote">Financial records remain in USD. Converted amounts are for display.</small></section></>}</div>
}
