"use client";
import { useEffect, useRef, useState } from "react";
import { MessageCircle, Send } from "lucide-react";
import { api } from "../lib/api";
import { ResourceFeedback, Pagination, useResource } from "./rewards/resource";
type Conversation={id:string;userId:string;name:string;email?:string;lastMessage:string;unread:number};
type Message={id:number;senderId:string;senderName:string;fromStaff:boolean;body:string;createdAt:string};
export function SupportChat({admin=false,userId}:{admin?:boolean;userId:string}){
 const [page,setPage]=useState(1);const [search,setSearch]=useState("");const [query,setQuery]=useState("");const [selected,setSelected]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const list=useResource<{items:Conversation[];total:number}>("/chat/conversations?page="+page+"&search="+encodeURIComponent(query),5000);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("conversation");if(!id)return;const timer=window.setTimeout(()=>setSelected(id),0);return ()=>window.clearTimeout(timer);},[]);
 const activeId=selected||list.data?.items[0]?.id; const active=list.data?.items.find(c=>c.id===activeId);
 async function start(email?:string){if(busy)return;setBusy(true);setError("");try{const row=await api<{id:string}>("/chat/conversations",{method:"POST",body:JSON.stringify(email?{email}:{})});setSelected(row.id);await list.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="ad-page-title"><div><span className="eyebrow">PRIVATE CONVERSATIONS</span><h1>{admin?"Support inbox":"Chat with support"}</h1><p>{admin?"Help users with their tasks, accounts and payments.":"Send a message to the admin team. Replies appear here and in your notifications."}</p></div></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className={"support-workspace "+(!admin?"support-user":"")}>
 {admin&&<aside className="support-inbox"><form onSubmit={e=>{e.preventDefault();setQuery(search);setPage(1);}}><input aria-label="Search users" placeholder="Search name or email" value={search} onChange={e=>setSearch(e.target.value)}/><button className="rw-button rw-button-secondary">Search</button></form><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void start(String(form.get("email")));}}><label>Start a conversation<input type="email" name="email" placeholder="User email address" required/></label><button className="rw-button rw-button-secondary" disabled={busy}>Open conversation</button></form><ResourceFeedback {...list} retry={list.refresh} initial={!list.data}/><nav aria-label="Conversations">{list.data?.items.map(c=><button key={c.id} className={activeId===c.id?"is-active":""} onClick={()=>setSelected(c.id)}><strong>{c.name}{c.unread>0&&<b>{c.unread}</b>}</strong><small>{c.email}</small><span>{c.lastMessage}</span></button>)}</nav>{list.data?.total===0&&<p>No conversations found.</p>}{list.data&&<Pagination page={page} total={list.data.total} onPage={setPage} busy={list.loading}/>}</aside>}
 {!admin&&<ResourceFeedback {...list} retry={list.refresh} initial={!list.data}/>} {activeId?<ChatThread key={activeId} id={activeId} name={active?.name||(admin?"User conversation":"Support team")} userId={userId}/>:<section className="panel rw-empty"><MessageCircle size={40}/><h2>{admin?"Choose a conversation":"How can we help?"}</h2><p>{admin?"Select a user or enter their email to start.":"Your conversation is private between you and the support team."}</p>{!admin&&<button className="rw-button rw-button-primary" disabled={busy||list.loading} onClick={()=>void start()}>Start conversation</button>}</section>}
 </div></>;
}
function ChatThread({id,name,userId}:{id:string;name:string;userId:string}){
 const [page,setPage]=useState(1);const [draft,setDraft]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const sent=useRef<{body:string;key:string}|null>(null);const read=useRef(0);const bottom=useRef<HTMLDivElement>(null);const scroll=useRef<HTMLDivElement>(null);const nearBottom=useRef(true);
 const messages=useResource<{items:Message[];total:number;readThrough:number}>("/chat/conversations/"+id+"/messages?page="+page,5000);const latest=messages.data?.items.at(-1)?.id||0;
 useEffect(()=>{if(page!==1||!latest)return;const mark=()=>{if(document.hidden||latest<=read.current)return;read.current=latest;void api("/chat/conversations/"+id+"/read",{method:"POST",body:JSON.stringify({lastReadId:latest})}).catch(()=>{read.current=0;});};mark();document.addEventListener("visibilitychange",mark);return()=>document.removeEventListener("visibilitychange",mark);},[id,latest,page]);
 useEffect(()=>{const box=scroll.current;if(page===1&&box&&nearBottom.current)bottom.current?.scrollIntoView({block:"nearest"});},[latest,page]);
 return <section className="support-thread"><header><MessageCircle size={24}/><div><h2>{name}</h2><small>Messages refresh every 5 seconds</small></div></header><ResourceFeedback {...messages} retry={messages.refresh} initial={!messages.data}/><div className="support-messages" ref={scroll} onScroll={()=>{const box=scroll.current;if(box)nearBottom.current=box.scrollHeight-box.scrollTop-box.clientHeight<150;}} role="log" aria-label="Conversation messages" aria-live="polite">{messages.data?.items.map(m=><article key={m.id} className={m.senderId===userId?"chat-bubble is-mine":"chat-bubble"}><strong>{m.senderId===userId?"You":m.fromStaff?m.senderName+" ? Support":m.senderName}</strong><p>{m.body}</p><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString()}{m.senderId===userId ? m.id<=(messages.data?.readThrough||0)?" - Read":" - Sent":""}</time></article>)}{messages.data?.total===0&&<p className="rw-empty">Send your first message below.</p>}<div ref={bottom}/></div><div className="support-history"><button disabled={page===1||messages.loading} onClick={()=>setPage(page-1)}>Newer messages</button><span>Page {page}</span><button disabled={!messages.data||page*50>=messages.data.total||messages.loading} onClick={()=>setPage(page+1)}>Older messages</button></div><form className="support-compose" onSubmit={async e=>{e.preventDefault();const body=draft.trim();if(!body||busy)return;setBusy(true);setError("");if(sent.current?.body!==body)sent.current={body,key:crypto.randomUUID()};try{await api("/chat/conversations/"+id+"/messages",{method:"POST",body:JSON.stringify({body,requestKey:sent.current.key})});setDraft("");sent.current=null;setPage(1);await messages.refresh();bottom.current?.scrollIntoView({block:"nearest"});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="sr-only" htmlFor={"message-"+id}>Your message</label><textarea id={"message-"+id} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Write your message..." maxLength={4000} rows={3} disabled={busy} required/><div><small>{draft.length}/4000</small><button className="rw-button rw-button-primary" disabled={busy||!draft.trim()}><Send size={16}/>{busy?"Sending...":"Send message"}</button></div>{error&&<p className="form-error" role="alert">{error} Your message is saved here so you can retry.</p>}</form></section>;
}
