/* eslint-disable @next/next/no-img-element */
"use client";
/* eslint-disable react-hooks/set-state-in-effect -- visibility hydrates from browser storage */
import Link from "next/link";
import { ArrowUpRight, Megaphone, Sparkles, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useResource } from "./rewards/resource";
type Promotion={id:string;title:string;description:string;imageUrl:string;destination:string;placement:string;updatedAt:string;mediaType?:"image"|"video"};
export function UserPromotionPopup(){const resource=useResource<Promotion[]>("/promotions");const [visible,setVisible]=useState(false);const popup=resource.data?.find(item=>item.placement==="popup");const key=popup?`rewardly-promotion:${popup.id}:${popup.updatedAt}`:"";useEffect(()=>{if(!popup)return;try{setVisible(localStorage.getItem(key)!=="dismissed");}catch{setVisible(true);}},[popup,key]);function dismiss(){setVisible(false);try{localStorage.setItem(key,"dismissed");}catch{}}if(!popup||!visible)return null;const external=!popup.destination.startsWith("/");return <div className="rw-promo-popup-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)dismiss();}}><section className="rw-promo-popup" role="dialog" aria-modal="true" aria-labelledby="rw-promo-title"><button className="rw-promo-close" onClick={dismiss} aria-label="Close announcement"><X size={19}/></button><div className="rw-promo-visual">{popup.mediaType==="video"?<video src={popup.imageUrl} autoPlay muted loop playsInline preload="auto" aria-label={popup.title}/>:<img src={popup.imageUrl} alt=""/>}<span><Megaphone size={14}/>New from Rewardly</span></div><div className="rw-promo-body"><span className="rw-promo-kicker"><Sparkles size={13}/>Promotion & update</span><h2 id="rw-promo-title">{popup.title}</h2>{popup.description&&<p>{popup.description}</p>}<div className="rw-promo-actions">{external?<a className="rw-button rw-button-primary" href={popup.destination} target="_blank" rel="noopener noreferrer" onClick={dismiss}>Learn more<ArrowUpRight size={16}/></a>:<Link className="rw-button rw-button-primary" href={popup.destination} onClick={dismiss}>View update<ArrowUpRight size={16}/></Link>}<button className="rw-button rw-button-secondary" onClick={dismiss}>Maybe later</button></div></div></section></div>}
