"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Check, Crown, Gift, Layers3, Rocket, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { AccountGate } from "../../components/account-gate";
import { Shell } from "../../components/shell";
import { Modal } from "../../components/rewards/primitives";
import { api } from "../../lib/api";
import { money } from "../../lib/rewards";

type Plan = { id: string; key: string; name: string; description: string; priceCents: number; durationDays: number | null; earningPotentialCents: number; minimumReferrals: number; minimumCompletedTasks: number; active: boolean; eligibility: { allowed: boolean; reasons: string[]; availableDepositCents: number; shortfallCents: number; qualifiedReferrals: number; completedTasks: number } };
type Purchase = { id: string; plan: Plan; status: string; expiresAt: string | null; bonusCents: number; referrerBonusCents: number; priceCents: number };
const planIcon = [Rocket, Crown, Sparkles];
function MembershipPage({ profile }: { profile: { user: { name: string } } }) {
  const [plans, setPlans] = useState<Plan[]>([]); const [current, setCurrent] = useState<Purchase | null>(null); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [purchasePlan, setPurchasePlan] = useState<Plan | null>(null);
  useEffect(() => { void (async () => { try { const [list, membership] = await Promise.all([api<Plan[]>("/membership/plans"), api<{ activeMembership: Purchase | null }>("/membership")]); setPlans(list); setCurrent(membership.activeMembership); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } })(); }, []);
  async function buy(plan: Plan) { setBusy(true); setError(""); setSuccess(""); try { const result = await api<Purchase>("/membership/purchase", { method: "POST", body: JSON.stringify({ planId: plan.id }) }); setCurrent(result); setSuccess(`${result.plan.name} is active${result.expiresAt ? ` until ${new Date(result.expiresAt).toLocaleDateString()}` : " with unlimited access"}.`); setPurchasePlan(null); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const maxTasks = Math.max(1, ...plans.map(plan => plan.minimumCompletedTasks)); const popular = plans[Math.min(1, Math.max(0, plans.length - 1))];
  return <Shell name={profile.user.name} admin={false}><section className="rw-membership-hero"><div><span className="eyebrow">MEMBERSHIP PLANS</span><h1>Upgrade your <em>experience.</em></h1><h2>More tasks. Higher rewards. Bigger opportunities.</h2><p>Choose the plan that fits your goals and unlock more ways to earn.</p></div><div className="rw-membership-art"><Rocket /><strong>Level up</strong><span>Earn more<br />Achieve more</span></div></section>
    {current && <div className="rw-membership-current"><ShieldCheck /><div><strong>{current.plan.name} membership is active</strong><span>{current.expiresAt ? `Renews or expires ${new Date(current.expiresAt).toLocaleDateString()}` : "Unlimited membership duration"}</span></div></div>}
    {error && <div className="form-error" role="alert">{error}</div>}{success && <div className="form-success" role="status">{success}</div>}{loading && <div className="panel">Loading membership plans…</div>}
    <div className="rw-plan-grid">{plans.map((plan, index) => { const Icon = planIcon[index % planIcon.length]; const isPopular = plan.id === popular?.id; const active = current?.plan.id === plan.id; const features = [plan.minimumCompletedTasks ? `Complete ${plan.minimumCompletedTasks}+ tasks to qualify` : "Premium task access", plan.earningPotentialCents ? `Up to ${money(plan.earningPotentialCents)} earning potential` : "More earning opportunities", plan.minimumReferrals ? `${plan.minimumReferrals} qualified referral requirement` : "Referral benefits included", plan.durationDays ? `${plan.durationDays} days of access` : "Unlimited access"]; return <article className={`rw-plan-card ${isPopular ? "is-popular" : ""} ${active ? "is-current" : ""}`} key={plan.id}>{isPopular && <span className="rw-plan-ribbon">Most popular</span>}<div className="rw-plan-heading"><span><Icon /></span><div><h2>{plan.name}</h2><p>{index === 0 ? "Perfect for beginners" : index === plans.length - 1 ? "For serious earners" : "For active users"}</p></div></div><div className="rw-plan-price"><strong>{money(plan.priceCents)}</strong><span>/ {plan.durationDays ? `${plan.durationDays} days` : "lifetime"}</span></div><p>{plan.description || "Unlock member tasks and more opportunities to earn rewards."}</p><ul>{features.map(feature => <li key={feature}><Check />{feature}</li>)}</ul>{!plan.eligibility.allowed && <div className="rw-plan-requirements">{plan.eligibility.reasons.map(reason => <span key={reason}>{reason}</span>)}</div>}{plan.eligibility.shortfallCents > 0 ? <Link className="rw-button rw-button-secondary rw-full" href="/payments">Add {money(plan.eligibility.shortfallCents)} to deposit balance</Link> : <button className="rw-button rw-button-primary rw-full" disabled={busy || active || !plan.eligibility.allowed} onClick={() => setPurchasePlan(plan)}>{active ? "Current membership" : `Choose ${plan.name}`}</button>}</article>; })}</div>
    {!!plans.length && <section className="rw-plan-comparison"><h2>Plan comparison</h2><div className="rw-plan-table"><div><strong>Features</strong>{plans.map(plan => <strong key={plan.id}>{plan.name}</strong>)}</div><div><span><Layers3 />Task qualification</span>{plans.map(plan => <span key={plan.id}>{plan.minimumCompletedTasks || "Open"}</span>)}</div><div><span><Gift />Earning potential</span>{plans.map(plan => <span key={plan.id}>{plan.earningPotentialCents ? money(plan.earningPotentialCents) : "Flexible"}</span>)}</div><div><span><Users />Referral requirement</span>{plans.map(plan => <span key={plan.id}>{plan.minimumReferrals || "None"}</span>)}</div><div><span><Crown />Premium access</span>{plans.map(plan => <span key={plan.id}>{plan.minimumCompletedTasks <= maxTasks ? <Check /> : <X />}</span>)}</div></div></section>}
    <section className="rw-plan-cta"><Gift /><div><strong>Upgrade your plan and unlock more opportunities</strong><span>Your deposit balance pays for membership. Reward points stay available for withdrawal.</span></div><Link href="/payments" className="rw-button">Add membership funds</Link></section>
    {purchasePlan && <Modal title="Confirm membership purchase" onClose={() => { if (!busy) setPurchasePlan(null); }}><span className="rw-tag">MEMBERSHIP UPGRADE</span><h2>{purchasePlan.name}</h2><p>{purchasePlan.description}</p><div className="rw-modal-reward"><span>Deposit balance charged</span><strong>{money(purchasePlan.priceCents)}</strong></div><p>{purchasePlan.durationDays ? `Access lasts ${purchasePlan.durationDays} days.` : "This plan has unlimited access."}</p><div className="rw-inline-actions"><button className="rw-button rw-button-secondary" disabled={busy} onClick={() => setPurchasePlan(null)}>Cancel</button><button className="rw-button rw-button-primary" disabled={busy} onClick={() => void buy(purchasePlan)}>{busy ? "Activating…" : `Activate for ${money(purchasePlan.priceCents)}`}</button></div></Modal>}
  </Shell>;
}
export default function Page() { return <AccountGate>{profile => <MembershipPage profile={profile} />}</AccountGate>; }
