export type ReferralRequirement = { required: number; qualified: number; remaining: number; met: boolean };
export type SurveyQuestion = { id: string; prompt: string; type: "text" | "single_choice" | "yes_no"; options: string[] };
export type SurveyAnswer = { questionId: string; answer: string };
export type Rules = { depositsEnabled?: boolean; withdrawalsEnabled?: boolean; minWithdrawalReferrals?: number; pointsPerUsd: number; minWithdrawalCents: number; maxWithdrawalCents: number; referralRewardPoints: number; referralRequiredTasks: number; referralsEnabled: boolean };
export type ProductItem = { id: string; name: string; description: string; imageUrl: string | null; position: number };
export type TaskRun = { surveyAnswers?: SurveyAnswer[] | null; rating?: number | null; round?: number; autoClaimOnVerification?: boolean; autoClaimOnApproval?: boolean; id: string; status: "in_progress" | "pending_review" | "approved" | "completed"; rewardPoints: number; verification: "code" | "manual" | "product_experience" | "image_preference" | "rating_review" | "survey"; proof: string | null; proofImage?: string | null; reviewReason: string | null; startedAt: string; completedAt: string | null };
export type Task = { favorite?: boolean; coverImage?: string | null; coverImageUrl?: string | null; coverVersion?: string | null; featured?: boolean; completedVisibleHours?: number; surveyQuestions?: SurveyQuestion[]; repeatHours?: number | null; autoClaimOnVerification?: boolean; autoClaimOnApproval?: boolean; nextAvailableAt?: string | null; round?: number; id: string; title: string; description: string; instructions: string; category: string; taskType: "standard" | "product_experience" | "image_preference" | "movie_review" | "music_review" | "survey"; products: ProductItem[]; rewardPoints: number; verification: "code" | "manual" | "product_experience" | "image_preference" | "rating_review" | "survey"; destinationUrl: string | null; requiresMembership: boolean; membershipPlanId: string | null; membershipPlan?: { id: string; name: string; key: string } | null; active: boolean; startsAt: string; endsAt: string | null; dailyLimit: number; totalLimit: number; createdAt: string; run: TaskRun | null; slotsRemaining: number };
export type Wallet = { referralRequirement: ReferralRequirement; points: number; reservedPoints: number; depositCents: number; reservedDepositCents: number; withdrawableDepositCents: number; usdCents: number; withdrawablePoints: number; withdrawableCents: number; eligible: boolean; eligibilityReason: string | null; todayPoints: number; rules: Rules };
export type Transaction = { id: string; kind: string; points: number; reservedPoints: number; depositCents: number; reservedDepositCents: number; description: string; createdAt: string };
export type Withdrawal = { mobileNumber?: string | null; payoutProofImage?: string | null; id: string; source: "points" | "deposit"; amountCents: number; points: number; pointsPerUsd: number; provider: string; destination: string; status: string; reason: string | null; paymentReference: string | null; createdAt: string };
export type PaymentMethod = { provider: "paypal" | "bank" | "crypto_usdt" | "crypto_btc" | "crypto_eth" | "mobile_money"; network: string; usdRateCents: number; label: string; enabled: boolean; recipient: string; instructions: string; minimumCents: number; maximumCents: number };
export type Deposit = { mobileNumber?: string | null; asset: "USDT" | "BTC" | "ETH" | null; network: string | null; cryptoAmount: string | null; usdRateCents: number | null; id: string; amountCents: number; provider: string; methodLabel: string; recipient: string; instructions: string; status: "awaiting_payment" | "pending_review" | "completed" | "rejected" | "cancelled"; paymentReference: string | null; proof: string | null; proofImage: string | null; reviewReason: string | null; createdAt: string; submittedAt: string | null; reviewedAt: string | null };
export const paymentStatus = (status: string) => ({ awaiting_payment: "Awaiting payment", pending_review: "Under review", pending: "Under review", approved: "Approved · awaiting payout", paid: "Paid", completed: "Completed", rejected: "Rejected", cancelled: "Cancelled" })[status] || status;
export function amountToCents(amount: string) {
  if (!/^\d+(\.\d{1,2})?$/.test(amount)) return 0;
  const cents = Number(amount.split(".")[0]) * 100 + Number((amount.split(".")[1] || "").padEnd(2, "0"));
  return Number.isSafeInteger(cents) && cents > 0 ? cents : 0;
}
export type Paged<T> = { items: T[]; total: number; page: number; pageSize: number };
export type ReferralItem = { id: string; name: string; emailVerified: boolean; completedTasks: number; requiredTasks: number; rewardPoints: number; verifiedAt: string | null; qualifiedAt: string | null; createdAt: string };
export type Referrals = Paged<ReferralItem> & { code: string; link: string; verified: number; qualified: number; earningsPoints: number; rules: Rules };
export const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
export const points = (value: number) => value.toLocaleString("en-US");
export const date = (value: string) => new Date(value).toLocaleString();
export const taskStatus = (task: Task) => !task.run ? "Available" : task.run.status === "completed" ? "Completed" : task.run.status === "pending_review" ? "Pending Review" : "In Progress";
