"use client";
import { useRef, useState } from "react";
import { BadgeDollarSign, CheckCircle2, Coins, Plus, Search, ShieldCheck, SlidersHorizontal, Trash2, UserRound } from "lucide-react";
import { AccountGate } from "../../../components/account-gate";
import { AdminShell } from "../../../components/admin-shell";
import { Modal } from "../../../components/rewards/primitives";
import { Pagination, RefreshButton, ResourceFeedback, useResource } from "../../../components/rewards/resource";
import { api, type Profile } from "../../../lib/api";
import { date, money, points, type Paged } from "../../../lib/rewards";

type UserRow = { deletedAt?: string | null; id: string; name: string; email: string; status: string; emailVerified: boolean; withdrawalEligible: boolean; withdrawalReason: string | null; referralCode: string; createdAt: string; wallet: { points: number; reservedPoints: number; depositCents: number; reservedDepositCents: number } | null; roles: { role: { name: string; key: string } }[] };
type Activity = Paged<Record<string, unknown>>;

function UserRecord({ user, profile, close, changed }: { user: UserRow; profile: Profile; close: () => void; changed: () => Promise<void> }) {
  const [tab, setTab] = useState("transactions"); const activity = useResource<Activity>(`/admin/users/${user.id}/activity?kind=${tab}`);
  const [mode, setMode] = useState<"edit" | "adjust" | "status" | "eligibility" | "delete" | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const requestKey = useRef(crypto.randomUUID());
  const regular = user.status !== "deleted" && user.roles.every(r => r.role.key === "user");
  async function save(path: string, body: unknown, method = "POST") { setBusy(true); setError(""); setMessage(""); try { await api(path, { method, body: JSON.stringify(body) }); setMessage("Change saved and recorded in the audit log."); setMode(null); requestKey.current = crypto.randomUUID(); await Promise.all([activity.refresh(), changed()]); if (method === "DELETE") close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const w = user.wallet;
  return <Modal title="User control record" onClose={() => { if (!busy) close(); }}><div className="ad-user-head"><div><span className="eyebrow">ACCOUNT {user.id}</span><h2>{user.name}</h2><small>{user.email} · joined {date(user.createdAt)}</small></div><span className={`status-badge ${user.status}`}>{user.status}</span></div>
    <div className="ad-detail-stats"><div>Points<strong>{points(w?.points || 0)}</strong></div><div>Reserved points<strong>{points(w?.reservedPoints || 0)}</strong></div><div>Deposit balance<strong>{money(w?.depositCents || 0)}</strong></div><div>Reserved cash<strong>{money(w?.reservedDepositCents || 0)}</strong></div></div>
    <div className="rw-inline-actions"><button className="rw-button rw-button-secondary" disabled={busy || !regular || user.id === profile.user.id} onClick={() => setMode("edit")}>Edit account</button><button className="rw-button rw-button-secondary" disabled={!regular || user.id === profile.user.id} onClick={() => setMode("adjust")}>Adjust balance</button><button className="rw-button rw-button-secondary" disabled={!regular || user.id === profile.user.id} onClick={() => setMode("status")}>{user.status === "active" ? "Suspend user" : "Activate user"}</button><button className="rw-button rw-button-secondary" disabled={!regular || user.id === profile.user.id} onClick={() => setMode("eligibility")}>Withdrawal access</button><button className="rw-button rw-button-danger" disabled={busy || !regular || user.id === profile.user.id || !profile.permissions.includes("users.manage")} onClick={() => setMode("delete")}><Trash2 size={16} />Delete user</button></div>
    {!regular && <p className="rw-notice">{user.status === "deleted" ? "Deleted account. Sign-in is disabled; historical records and balances are retained." : "Staff accounts are protected from this user-management workflow."}</p>}{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}
    {mode === "delete" && <form className="profile-form ad-section" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void save(`/admin/users/${user.id}`, { email: f.get("email"), reason: f.get("reason") }, "DELETE"); }}><h3>Delete this user account?</h3><p>This removes sign-in access, clears login credentials, and hides the user from the current directory. Reward balances, task history, payments, and audit records remain available under Deleted accounts. Unsubmitted deposit requests will be cancelled. Resolve submitted deposits and open withdrawals first.</p><label>Type {user.email} to confirm<input type="email" name="email" autoComplete="off" required disabled={busy} /></label><label>Reason for deletion<textarea name="reason" minLength={10} maxLength={500} required disabled={busy} /></label><div className="rw-inline-actions"><button className="rw-button rw-button-danger" disabled={busy}>{busy ? "Deleting?" : "Confirm deletion"}</button><button type="button" className="rw-button rw-button-secondary" disabled={busy} onClick={() => setMode(null)}>Cancel</button></div></form>}
    {mode === "edit" && <form className="profile-form ad-section" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void save(`/admin/users/${user.id}/profile`, { name: f.get("name"), email: f.get("email"), reason: f.get("reason") }, "PATCH"); }}><h3>Edit profile</h3><label>Name<input name="name" defaultValue={user.name} minLength={2} maxLength={80} required /></label><label>Email<input type="email" name="email" defaultValue={user.email} required /><small>Changing email revokes sessions and requires the user to verify the new address.</small></label><label>Reason<input name="reason" minLength={10} maxLength={500} required /></label><button className="rw-button rw-button-primary" disabled={busy}>Save user details</button></form>}
    {mode === "adjust" && <form className="profile-form ad-section" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const source = String(f.get("source")); const raw = Number(f.get("delta")); const delta = source === "deposit" ? Math.round(raw * 100) : Math.round(raw); void save(`/admin/users/${user.id}/adjustment`, { source, delta, reason: f.get("reason"), requestKey: requestKey.current }); }}><h3>Manual balance adjustment</h3><label>Balance<select name="source"><option value="points">Reward points</option><option value="deposit">Deposit USD</option></select></label><label>Adjustment<input name="delta" type="number" step="0.01" required /><small>Use a positive number to credit or a negative number to deduct. Deposit amounts are entered in USD.</small></label><label>Recorded reason<input name="reason" minLength={10} maxLength={500} required /></label><button className="rw-button rw-button-primary" disabled={busy}>Apply adjustment</button></form>}
    {mode === "status" && <form className="profile-form ad-section" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void save(`/admin/users/${user.id}/status`, { status: user.status === "active" ? "suspended" : "active", reason: f.get("reason") }); }}><h3>{user.status === "active" ? "Suspend" : "Activate"} account</h3><p>{user.status === "active" ? "Suspension revokes every active session and blocks sign-in." : "Activation restores account access."}</p><label>Recorded reason<input name="reason" minLength={10} maxLength={500} required /></label><button className="rw-button rw-button-primary" disabled={busy}>Confirm account change</button></form>}
    {mode === "eligibility" && <form className="profile-form ad-section" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void save("/admin/rewards/eligibility", { email: user.email, eligible: f.get("eligible") === "yes", reason: f.get("reason") }, "PATCH"); }}><h3>Withdrawal access</h3><label>Eligibility<select name="eligible" defaultValue={user.withdrawalEligible ? "yes" : "no"}><option value="yes">Allow withdrawals</option><option value="no">Place withdrawals on hold</option></select></label><label>Recorded reason<input name="reason" minLength={10} maxLength={500} required /></label><button className="rw-button rw-button-primary" disabled={busy}>Update eligibility</button></form>}
    <section className="ad-section"><div className="section-top"><h3>User activity</h3><RefreshButton onClick={activity.refresh} busy={activity.loading} /></div><div className="rw-task-filters">{["transactions", "tasks", "deposits", "withdrawals", "referrals"].map(value => <button key={value} className={tab === value ? "is-active" : ""} onClick={() => setTab(value)}>{value}</button>)}</div><ResourceFeedback {...activity} retry={activity.refresh} initial={!activity.data} />{activity.data?.items.map((item, index) => <article className="ad-activity" key={String(item.id || index)}><div><strong>{String(item.description || item.status || item.kind || "Record")}</strong><small>{item.createdAt ? date(String(item.createdAt)) : ""}</small></div><details><summary>Full record</summary><pre>{JSON.stringify(item, null, 2)}</pre></details></article>)}{activity.data?.total === 0 && <p>No records in this category.</p>}</section>
  </Modal>;
}

function CreateUser({ close, created }: { close: () => void; created: (message: string) => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <Modal title="Add user" onClose={() => { if (!busy) close(); }}><h2>Add a user</h2><p>Create a regular user account. The user must verify their email before signing in.</p><form className="profile-form" onSubmit={async e => { e.preventDefault(); if (busy) return; const form = new FormData(e.currentTarget); setBusy(true); setError(""); try { const result = await api<{ verificationSent: boolean }>("/admin/users", { method: "POST", body: JSON.stringify({ name: form.get("name"), email: form.get("email"), password: form.get("password"), reason: form.get("reason") }) }); await created(result.verificationSent ? "User created. A verification email was sent; the user can sign in after verifying." : "User created, but verification email could not be sent. The user can request it again on the Verify email page."); close(); } catch (failure) { setError((failure as Error).message); } finally { setBusy(false); } }}><label>Full name<input name="name" minLength={2} maxLength={80} required disabled={busy} /></label><label>Email<input type="email" name="email" maxLength={254} required disabled={busy} /></label><label>Initial password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required disabled={busy} /><small>At least 12 characters. Share it securely with the user.</small></label><label>Recorded reason<textarea name="reason" minLength={10} maxLength={500} required disabled={busy} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="rw-button rw-button-primary" disabled={busy}>{busy ? "Creating?" : "Create user"}</button></form></Modal>;
}

function UsersPage({ profile }: { profile: Profile }) {
  const [creating, setCreating] = useState(false); const [message, setMessage] = useState("");
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [selected, setSelected] = useState<UserRow | null>(null);
  const resource = useResource<Paged<UserRow>>(`/admin/users?page=${page}&status=${status}&search=${encodeURIComponent(query)}`);
  const rows = resource.data?.items || [];
  const pagePoints = rows.reduce((total, user) => total + (user.wallet?.points || 0), 0);
  const pageDeposits = rows.reduce((total, user) => total + (user.wallet?.depositCents || 0), 0);
  const verified = rows.filter(user => user.emailVerified).length;
  return <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><div className="ad-users-page"><div className="ad-page-title ad-users-title"><div><span className="eyebrow">USER DATA & CONTROLS</span><h1>Users and balances</h1><p>Find accounts, review access, and manage balances from one clear workspace.</p></div><div className="rw-inline-actions">{profile.permissions.includes("users.manage") && <button className="rw-button rw-button-primary" onClick={() => { setSelected(null); setCreating(true); setMessage(""); }}><Plus size={17} />Add user</button>}<RefreshButton onClick={resource.refresh} busy={resource.loading} /></div></div>{message && <p className="form-success" role="status">{message}</p>}
    <section className="ad-user-metrics" aria-label="Account summary"><article><span><UserRound size={18}/></span><div><small>Matching accounts</small><strong>{resource.data?.total || 0}</strong></div></article><article><span><CheckCircle2 size={18}/></span><div><small>Verified on this page</small><strong>{verified}</strong></div></article><article><span><Coins size={18}/></span><div><small>Points on this page</small><strong>{points(pagePoints)}</strong></div></article><article><span><BadgeDollarSign size={18}/></span><div><small>Deposits on this page</small><strong>{money(pageDeposits)}</strong></div></article></section>
    <form className="ad-user-search" onSubmit={e => { e.preventDefault(); setPage(1); setQuery(search.trim()); }}><div className="ad-user-search-input"><Search size={19}/><label className="sr-only" htmlFor="user-search">Search users</label><input id="user-search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by name or email" /></div><select aria-label="Account status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="all">Current accounts</option><option value="active">Active accounts</option><option value="suspended">Suspended accounts</option><option value="deleted">Deleted accounts</option></select><button className="rw-button rw-button-primary"><Search size={17} />Search</button></form><ResourceFeedback {...resource} retry={resource.refresh} initial={!resource.data} />
    <section className="panel ad-user-directory"><div className="section-top"><div><span className="eyebrow">ACCOUNT DIRECTORY</span><h2>{status === "deleted" ? "Deleted accounts" : "Current accounts"}</h2></div><span className="ad-count">{resource.data?.total || 0} accounts</span></div><div className="ad-user-list">{rows.map(user => <article className="ad-user-card" key={user.id}><div className="ad-user-identity"><span className="ad-user-avatar">{user.name.slice(0,1).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div><div className="ad-user-access"><span className={`status-badge ${user.status}`}>{user.status}</span><small>{user.emailVerified ? <><ShieldCheck size={13}/>Verified email</> : "Email unverified"}</small></div><div className="ad-user-role"><small>Role</small><strong>{user.roles.map(r => r.role.name).join(", ")}</strong></div><div className="ad-user-balance"><small>Reward points</small><strong>{points(user.wallet?.points || 0)}</strong><span>{points(user.wallet?.reservedPoints || 0)} reserved</span></div><div className="ad-user-balance"><small>Deposit balance</small><strong>{money(user.wallet?.depositCents || 0)}</strong><span>{money(user.wallet?.reservedDepositCents || 0)} reserved</span></div><button className="rw-button rw-button-secondary ad-open-user" onClick={() => setSelected(user)}><SlidersHorizontal size={15} />Manage</button></article>)}</div>{rows.length === 0 && !resource.loading && <div className="ad-user-empty"><Search size={25}/><h3>No accounts found</h3><p>Change the search or account status and try again.</p></div>}{resource.data && <Pagination page={page} total={resource.data.total} onPage={setPage} busy={resource.loading} />}</section>
    {creating && <CreateUser close={() => setCreating(false)} created={async message => { setMessage(message); await resource.refresh(); }} />}
    {selected && <UserRecord key={selected.id} user={selected} profile={profile} close={() => setSelected(null)} changed={async () => { await resource.refresh(); const next = await api<UserRow>(`/admin/users/${selected.id}`); setSelected(next); }} />}
  </div></AdminShell>;
}

export default function Page() { return <AccountGate>{profile => profile.permissions.includes("users.read") ? <UsersPage profile={profile} /> : <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><h1>Admin access required</h1></AdminShell>}</AccountGate>; }
