/* eslint-disable @next/next/no-img-element */
"use client";
import { useState } from "react";
import Link from "next/link";
import { AccountGate } from "../../../components/account-gate";
import { AdminShell } from "../../../components/admin-shell";
import { Modal } from "../../../components/rewards/primitives";
import { Pagination, RefreshButton, ResourceFeedback, useResource } from "../../../components/rewards/resource";
import { type Profile } from "../../../lib/api";
import { date, money, paymentStatus, type Paged } from "../../../lib/rewards";

type Kind = "deposits" | "withdrawals";
type Ledger = { id: string; reference: string; kind: string; points: number; reservedPoints: number; depositCents: number; reservedDepositCents: number; createdAt: string };
type Payment = { id: string; status: string; amountCents: number; provider: string; asset?: string | null; source?: string; paymentReference?: string | null; createdAt: string; submittedAt?: string | null; reviewedAt?: string | null; proof?: string | null; reviewReason?: string | null; reason?: string | null; destination?: string; user: { name: string; email: string }; matched: boolean; issues: string[]; expectedReferences: string[]; ledger: Ledger[] };
type Detail = { item: Payment & { proofImage?: string | null; payoutProofImage?: string | null; recipient?: string; instructions?: string }; matched: boolean; issues: string[]; expectedReferences: string[]; ledger: Ledger[]; audit: { id: string; action: string; actorId: string | null; reason: string | null; createdAt: string }[] };

function Record({ kind, id, close }: { kind: Kind; id: string; close: () => void }) {
  const resource = useResource<Detail>(`/admin/reconciliation/${kind}/${id}`); const data = resource.data; const item = data?.item;
  return <Modal title="Payment reconciliation record" onClose={close}><h2>Payment evidence</h2><ResourceFeedback {...resource} retry={resource.refresh} initial={!data}/>{item && <div className="ad-reconcile-detail"><div className="ad-reconcile-summary"><strong>{money(item.amountCents)}</strong><span>{paymentStatus(item.status)} · {item.provider}{item.asset ? ` / ${item.asset}` : ""}</span><small>{item.user.name} · {item.user.email}</small><small>Record: {item.id}</small></div><div className={data.matched ? "form-success" : "form-error"} role="status">{data.matched ? "Ledger matches this payment's current status." : data.issues.join("; ")}</div><section><h3>Payment proof</h3>{kind === "deposits" ? <><p>Requested {date(item.createdAt)} · Submitted {item.submittedAt ? date(item.submittedAt) : "not yet"} · Reviewed {item.reviewedAt ? date(item.reviewedAt) : "not yet"}</p>{item.recipient && <p>Receiving destination: <strong className="rw-selectable">{item.recipient}</strong></p>}{item.paymentReference && <p>Transaction reference: <strong className="rw-selectable">{item.paymentReference}</strong></p>}{item.proof && <p>{item.proof}</p>}{item.proofImage ? <img className="rw-receipt-image" src={item.proofImage} alt="Submitted deposit receipt"/> : <p>No receipt image submitted.</p>}{item.reviewReason && <p>Review note: {item.reviewReason}</p>}</> : <><p>Requested {date(item.createdAt)} · Payout destination: <strong className="rw-selectable">{item.destination || "Not recorded"}</strong></p><p>Payout reference: {item.paymentReference || "Not recorded"}</p>{item.payoutProofImage ? <img className="rw-receipt-image" src={item.payoutProofImage} alt="Staff payout receipt"/> : <p>No payout receipt image attached.</p>}{item.reason && <p>Decision reason: {item.reason}</p>}</>}</section><section><h3>Ledger entries</h3>{data.ledger.length ? data.ledger.map(entry => <article className="ad-reconcile-ledger" key={entry.id}><strong>{entry.kind}</strong><code>{entry.reference}</code><small>{date(entry.createdAt)} · Points {entry.points} / reserved {entry.reservedPoints} · Deposit {money(entry.depositCents)} / reserved {money(entry.reservedDepositCents)}</small></article>) : <p>No ledger entries for this payment.</p>}</section><section><h3>Decision history</h3>{data.audit.length ? data.audit.map(event => <article className="ad-reconcile-ledger" key={event.id}><strong>{event.action}</strong><small>{date(event.createdAt)} · Staff ID: {event.actorId || "System"}</small>{event.reason && <p>{event.reason}</p>}</article>) : <p>No audit events recorded.</p>}</section></div>}</Modal>;
}

function Reconciliation({ profile }: { profile: Profile }) {
  const [kind, setKind] = useState<Kind>("deposits"); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<string | null>(null);
  const resource = useResource<Paged<Payment>>(`/admin/reconciliation?kind=${kind}&page=${page}&search=${encodeURIComponent(query)}`);
  function changeKind(value: Kind) { setKind(value); setPage(1); setSelected(null); }
  return <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><div className="ad-page-title"><div><span className="eyebrow">PAYMENT CONTROL</span><h1>Reconciliation</h1><p>Trace each deposit and withdrawal from payment evidence to its ledger entries. Exceptions are flagged for investigation.</p></div><RefreshButton onClick={resource.refresh} busy={resource.loading}/></div><div className="ad-reconcile-tabs" role="tablist" aria-label="Payment type"><button type="button" role="tab" aria-selected={kind === "deposits"} onClick={() => changeKind("deposits")}>Deposits</button><button type="button" role="tab" aria-selected={kind === "withdrawals"} onClick={() => changeKind("withdrawals")}>Withdrawals</button></div><form className="ad-toolbar" onSubmit={event => { event.preventDefault(); setPage(1); setQuery(search.trim()); }}><input aria-label="Search payments" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search payment ID, name, or email"/><button className="rw-button rw-button-secondary">Search</button></form><ResourceFeedback {...resource} retry={resource.refresh} initial={!resource.data}/><section className="panel ad-section"><div className="section-top"><div><h2>{kind === "deposits" ? "Deposit" : "Withdrawal"} records</h2><p>Ledger checks reflect the current status of each record.</p></div><Link href={kind === "deposits" ? "/admin/payments" : "/admin/withdrawals"} className="rw-button rw-button-secondary">Open payment controls</Link></div><div className="ad-reconcile-list">{resource.data?.items.map(item => <article key={item.id}><div className="ad-reconcile-top"><div><strong>{money(item.amountCents)} · {item.user.name}</strong><small>{item.user.email} · {date(item.createdAt)}</small></div><span className={`rw-state-badge ${item.status}`}>{paymentStatus(item.status)}</span></div><div className="ad-reconcile-bottom"><span className={item.matched ? "ad-ledger-ok" : "ad-ledger-issue"}>{item.matched ? "Ledger matched" : `${item.issues.length} ledger issue${item.issues.length === 1 ? "" : "s"}`}</span><small>{item.asset || item.provider}{item.paymentReference ? ` · ${item.paymentReference}` : ""}</small><button className="rw-button rw-button-secondary" onClick={() => setSelected(item.id)}>View evidence & ledger</button></div>{!item.matched && <p className="ad-reconcile-warning">{item.issues.join("; ")}</p>}</article>)}</div>{resource.data?.items.length === 0 && <p>No matching payments.</p>}{resource.data && <Pagination page={page} total={resource.data.total} onPage={setPage} busy={resource.loading}/>}</section>{selected && <Record kind={kind} id={selected} close={() => setSelected(null)}/>}</AdminShell>;
}
export default function Page() { return <AccountGate>{profile => profile.permissions.includes("rewards.manage") ? <Reconciliation profile={profile}/> : <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><p>Admin access required.</p></AdminShell>}</AccountGate>; }
