"use client";
import { useState } from "react";
import { Search } from "lucide-react";
import { AccountGate } from "../../../components/account-gate";
import { AdminShell } from "../../../components/admin-shell";
import { Pagination, RefreshButton, ResourceFeedback, useResource } from "../../../components/rewards/resource";
import { type Profile } from "../../../lib/api";
import { date, points, type Paged } from "../../../lib/rewards";
type Referral = { id: string; rewardPoints: number; requiredTasks: number; qualifiedAt: string | null; createdAt: string; inviter: { name: string; email: string }; invitee: { name: string; email: string } };
function Referrals({ profile }: { profile: Profile }) {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const resource = useResource<Paged<Referral>>(`/admin/referrals?page=${page}&search=${encodeURIComponent(query)}`);
  return <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><div className="ad-page-title"><div><span className="eyebrow">REFERRAL DATA</span><h1>Referral management</h1><p>See every invitation, qualification rule, and credited reward relationship.</p></div><RefreshButton onClick={resource.refresh} busy={resource.loading} /></div><form className="ad-toolbar" onSubmit={e => { e.preventDefault(); setQuery(search); setPage(1); }}><input aria-label="Search referrals" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search inviter or invited user email" /><button className="rw-button rw-button-primary"><Search size={17} />Search</button></form><ResourceFeedback {...resource} retry={resource.refresh} initial={!resource.data} /><section className="panel"><div className="section-top"><h2>Referral records</h2><span className="ad-count">{resource.data?.total || 0}</span></div><div className="ad-table-wrap"><table className="ad-table"><thead><tr><th>Inviter</th><th>Invited user</th><th>Terms</th><th>Status</th><th>Registered</th></tr></thead><tbody>{resource.data?.items.map(item => <tr key={item.id}><td><strong>{item.inviter.name}</strong><small>{item.inviter.email}</small></td><td><strong>{item.invitee.name}</strong><small>{item.invitee.email}</small></td><td>{points(item.rewardPoints)} points<small>{item.requiredTasks} claimed tasks required</small></td><td><span className={`rw-state-badge ${item.qualifiedAt ? "completed" : "pending_review"}`}>{item.qualifiedAt ? "Qualified" : "In progress"}</span>{item.qualifiedAt && <small>{date(item.qualifiedAt)}</small>}</td><td>{date(item.createdAt)}</td></tr>)}</tbody></table></div>{resource.data && <Pagination page={page} total={resource.data.total} onPage={setPage} busy={resource.loading} />}</section></AdminShell>;
}
export default function Page() { return <AccountGate>{p => p.permissions.includes("rewards.manage") ? <Referrals profile={p} /> : <AdminShell name={p.user.name} roles={p.roles} permissions={p.permissions}><h1>Admin access required</h1></AdminShell>}</AccountGate>; }
