import Link from "next/link";
import { ArrowRight, Check, ClipboardCheck, Coins, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { Shell } from "../../components/shell";
const steps = [
  { n: "01", title: "Make it yours", description: "Register, verify your email, and set up your account. A secure place for your next little win.", icon: UserRound, available: true },
  { n: "02", title: "Find your fit", description: "Choose an approved task, follow its instructions, and submit the required evidence for verification.", icon: ClipboardCheck, available: true },
  { n: "03", title: "Watch it add up", description: "Claim approved points, track your rewards, and request eligible withdrawals under the published rules.", icon: Coins, available: true },
];
export default function Page() {
  return <Shell preview><div className="page-heading"><div><div className="eyebrow">THE REWARDLY WAY</div><h1>Small steps. Clear rewards.</h1><p>A little time, a little progress, and a clear path forward.</p></div><span className="pill"><Sparkles size={13} />Your journey starts here</span></div><div className="rw-feature-steps">{steps.map(({n,title,description,icon:Icon,available}) => <section className="panel" key={n}><div className="rw-feature-step-top"><span className="rw-step-icon"><Icon size={25} /></span><span className="rw-step-index">{n}</span></div><h2>{title}</h2><p>{description}</p><span className={`rw-step-status ${available ? "is-ready" : ""}`}>{available ? <Check size={13} /> : <Sparkles size={13} />}{available ? "Ready to explore" : "Coming in a later module"}</span></section>)}</div><section className="rw-feature-hero rw-start-hero"><div className="rw-feature-copy"><span className="rw-tag"><ShieldCheck size={12} />YOUR PACE. YOUR POSSIBILITIES.</span><h2>Good things start<br />with one small step.</h2><p>Create your account and make yourself at home. Your rewards journey can grow from there.</p><Link href="/register" className="rw-button rw-button-primary">Create your account<ArrowRight size={17} /></Link></div><div className="rw-feature-art" aria-hidden="true"><span className="rw-feature-orbit" /><span className="rw-feature-main-icon"><Sparkles size={55} /></span><span className="rw-feature-spark">✦</span></div></section></Shell>;
}
