/* eslint-disable @next/next/no-img-element */
"use client";
import { useState } from "react";
import { usePathname } from "next/navigation";
import { AlertTriangle, ArrowDownToLine, Banknote, Bitcoin, CheckCircle2, Copy, Landmark, Search, Settings2, ShieldCheck, WalletCards } from "lucide-react";
import { AccountGate } from "../../../components/account-gate";
import { AdminShell } from "../../../components/admin-shell";
import { Modal } from "../../../components/rewards/primitives";
import { Pagination, RefreshButton, ResourceFeedback, useResource } from "../../../components/rewards/resource";
import { api, type Profile } from "../../../lib/api";
import { imageData } from "../../../lib/image-upload";
import { amountToCents, date, money, paymentStatus, points, type Deposit, type Paged, type PaymentMethod, type Withdrawal } from "../../../lib/rewards";

type AdminDeposit = Deposit & { user: { name: string; email: string } };
type AdminWithdrawal = Withdrawal & { user: { id: string; name: string; email: string; withdrawalEligible: boolean; status: string; emailVerified: boolean } };
type Metrics = { pendingDepositCount: number; pendingDepositCents: number; awaitingPaymentCount: number; rejectedDepositCount: number; openWithdrawalCount: number; openWithdrawalCents: number; paidWithdrawalCents: number; userDepositCents: number; reservedDepositCents: number; enabledMethodCount: number };
type PaymentsData = Paged<AdminDeposit> & { availability?: { depositsEnabled: boolean; withdrawalsEnabled: boolean }; methods: PaymentMethod[]; completedCents: number; metrics: Metrics };

function DepositReview({ item, close, saved }: { item: AdminDeposit; close: () => void; saved: () => Promise<void> }) {
  const [amount, setAmount] = useState((item.amountCents / 100).toFixed(2)); const [confirmed, setConfirmed] = useState(false); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); setMessage("Copied."); } catch { setError("Copy failed. Select the value manually."); } }
  async function decide(decision: "approve" | "reject") { setBusy(true); setError(""); try { await api(`/admin/payments/deposits/${item.id}/review`, { method: "POST", body: JSON.stringify({ decision, reason, ...(decision === "approve" ? { confirmedAmountCents: amountToCents(amount) } : {}) }) }); await saved(); close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title="Deposit control record" onClose={() => { if (!busy) close(); }}><div className="ad-payment-record-head"><div><span className="eyebrow">DEPOSIT {item.id}</span><h2>{money(item.amountCents)} · {item.asset || item.methodLabel}</h2><p>{item.user.name} · {item.user.email}</p>{item.mobileNumber && <p>Mobile: {item.mobileNumber}</p>}</div><span className={`rw-state-badge ${item.status}`}>{paymentStatus(item.status)}</span></div>
    <div className="ad-payment-route"><div><small>REQUESTED</small><strong>{date(item.createdAt)}</strong></div><span>→</span><div><small>SUBMITTED</small><strong>{item.submittedAt ? date(item.submittedAt) : "No proof"}</strong></div><span>→</span><div><small>REVIEWED</small><strong>{item.reviewedAt ? date(item.reviewedAt) : "Pending"}</strong></div></div>
    {item.asset && <div className="ad-crypto-facts"><div><small>ASSET</small><strong>{item.cryptoAmount} {item.asset}</strong></div><div><small>NETWORK</small><strong>{item.network}</strong></div><div><small>RATE</small><strong>1 {item.asset} = {money(item.usdRateCents || 0)}</strong></div></div>}
    <section className="ad-payment-evidence"><div className="section-top"><h3>Receiving destination</h3><button className="rw-icon-button" aria-label="Copy destination" onClick={() => void copy(item.recipient)}><Copy size={17} /></button></div><p className="rw-proof-text rw-selectable">{item.recipient}</p><small>Instructions shown to user</small><p>{item.instructions}</p></section>
    <section className="ad-payment-evidence"><div className="section-top"><h3>Submitted evidence</h3>{item.asset !== "USDT" && item.paymentReference && <button className="rw-icon-button" aria-label="Copy reference" onClick={() => void copy(item.paymentReference || "")}><Copy size={17} /></button>}</div>{item.asset !== "USDT" && <><small>Reference / transaction hash</small><p className="rw-proof-text rw-selectable">{item.paymentReference || "Not submitted"}</p></>}{item.proof && <><small>User payment details</small><p className="rw-proof-text">{item.proof}</p></>}{item.proofImage && <><small>Uploaded receipt</small><img className="rw-receipt-image" src={item.proofImage} alt="User payment receipt" /></>}</section>
    {item.reviewReason && <div className="rw-notice"><strong>Latest review</strong><p>{item.reviewReason}</p></div>}{message && <p className="form-success">{message}</p>}{error && <p className="form-error" role="alert">{error}</p>}
    {item.status === "pending_review" && <div className="profile-form ad-review-actions"><label>Review reason<textarea rows={3} value={reason} onChange={e => setReason(e.target.value)} minLength={10} maxLength={500} required /></label><label>Confirmed USD received<input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} /></label><label className="rw-check-field"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />I verified the asset, network, receiving destination, uploaded receipt, and exact funds received.</label><div className="rw-inline-actions"><button className="rw-button rw-button-primary" disabled={busy || !confirmed || amountToCents(amount) !== item.amountCents || reason.trim().length < 10} onClick={() => void decide("approve")}><CheckCircle2 size={17} />Confirm and credit</button><button className="rw-button rw-button-danger" disabled={busy || reason.trim().length < 10} onClick={() => void decide("reject")}><AlertTriangle size={17} />Reject with reason</button></div></div>}
  </Modal>;
}

function WithdrawalReview({ item, close, saved }: { item: AdminWithdrawal; close: () => void; saved: () => Promise<void> }) {
  const [reason, setReason] = useState(""); const [reference, setReference] = useState(""); const [payoutProofImage, setPayoutProofImage] = useState(""); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const eligible = item.user.withdrawalEligible && item.user.status === "active" && item.user.emailVerified;
  async function decide(decision: "approve" | "reject" | "paid") { setBusy(true); setError(""); try { await api(`/admin/rewards/withdrawals/${item.id}`, { method: "POST", body: JSON.stringify({ decision, reason, ...(decision === "paid" && reference.trim() ? { paymentReference: reference } : {}), ...(decision === "paid" && payoutProofImage ? { payoutProofImage } : {}) }) }); await saved(); close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title="Withdrawal control record" onClose={() => { if (!busy) close(); }}><div className="ad-payment-record-head"><div><span className="eyebrow">WITHDRAWAL {item.id}</span><h2>{money(item.amountCents)} · {item.provider.toUpperCase()}</h2><p>{item.user.name} · {item.user.email}</p>{item.mobileNumber && <p>Mobile: {item.mobileNumber}</p>}</div><span className={`rw-state-badge ${item.status}`}>{paymentStatus(item.status)}</span></div><div className="ad-crypto-facts"><div><small>SOURCE</small><strong>{item.source === "points" ? `${points(item.points)} points` : "Deposited USD"}</strong></div><div><small>REQUESTED</small><strong>{date(item.createdAt)}</strong></div><div><small>ELIGIBILITY</small><strong>{eligible ? "Eligible" : "On hold"}</strong></div></div><section className="ad-payment-evidence"><h3>Payout destination</h3><p className="rw-proof-text rw-selectable">{item.destination}</p>{item.paymentReference && <><small>Payment reference</small><p>{item.paymentReference}</p></>}{item.payoutProofImage && <img className="rw-receipt-image" src={item.payoutProofImage} alt="Payout receipt"/>}</section>{!eligible && <p className="form-error">This user is not eligible for payment. Reject to release the reservation.</p>}{item.reason && <div className="rw-notice"><p>{item.reason}</p></div>}{error && <p className="form-error">{error}</p>}
    {["pending", "approved"].includes(item.status) && <div className="profile-form ad-review-actions"><label>Recorded reason<textarea rows={3} value={reason} onChange={e => setReason(e.target.value)} minLength={10} maxLength={500} required /></label>{item.status === "approved" && <><label>Payment reference (optional)<input value={reference} onChange={e => setReference(e.target.value)} minLength={5} maxLength={150} /></label><label>Payout receipt image (optional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { setPayoutProofImage(await imageData(file)); setError(""); } catch (failure) { setError((failure as Error).message); } }} /><small>JPG, PNG, or WebP under 2 MB. The receipt will appear in reconciliation.</small></label>{payoutProofImage && <img className="rw-receipt-image" src={payoutProofImage} alt="Payout receipt preview"/>}<label className="rw-check-field"><input type="checkbox" checked={sent} onChange={e => setSent(e.target.checked)} />I confirm the payment has been sent.</label></>}<div className="rw-inline-actions">{item.status === "pending" ? <button className="rw-button rw-button-primary" disabled={busy || !eligible || reason.trim().length < 10} onClick={() => void decide("approve")}>Approve request</button> : <button className="rw-button rw-button-primary" disabled={busy || !eligible || !sent || reason.trim().length < 10} onClick={() => void decide("paid")}>Record payment sent</button>}<button className="rw-button rw-button-danger" disabled={busy || reason.trim().length < 10} onClick={() => void decide("reject")}>Reject and release</button></div></div>}
  </Modal>;
}

function MethodEditor({ item, close, saved }: { item: PaymentMethod; close: () => void; saved: () => Promise<void> }) {
  const crypto = item.provider.startsWith("crypto_"); const coin = item.provider.replace("crypto_", "").toUpperCase(); const [values, setValues] = useState(item); const [rate, setRate] = useState((item.usdRateCents / 100).toFixed(2)); const [minimum, setMinimum] = useState((item.minimumCents / 100).toFixed(2)); const [maximum, setMaximum] = useState((item.maximumCents / 100).toFixed(2)); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await api(`/admin/payments/methods/${item.provider}`, { method: "PATCH", body: JSON.stringify({ network: values.network, usdRateCents: amountToCents(rate), label: values.label, recipient: values.recipient, instructions: values.instructions, enabled: values.enabled, minimumCents: amountToCents(minimum), maximumCents: amountToCents(maximum), reason }) }); await saved(); close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title={`Configure ${crypto ? coin : item.label}`} onClose={() => { if (!busy) close(); }}><form className="profile-form" onSubmit={submit}><label>Display name<input value={values.label} onChange={e => setValues({ ...values, label: e.target.value })} minLength={3} maxLength={80} required /></label>{crypto && <label>Network<select value={values.network} onChange={e => setValues({ ...values, network: e.target.value })}>{(coin === "USDT" ? ["TRON (TRC20)", "Ethereum (ERC20)"] : coin === "BTC" ? ["Bitcoin"] : ["Ethereum"]).map(network => <option key={network}>{network}</option>)}</select></label>}<label>{crypto ? "Receiving wallet address" : item.provider === "mobile_money" ? "Receiving mobile number (country code optional)" : item.provider === "bank" ? "Bank receiving details" : "Receiving account"}<textarea rows={4} required={values.enabled} value={values.recipient} onChange={e => setValues({ ...values, recipient: e.target.value })} maxLength={1000} /></label>{crypto && <label>USD value of 1 {coin}<input inputMode="decimal" value={rate} onChange={e => setRate(e.target.value)} required={values.enabled} /><small>This rate is saved into every new request.</small></label>}{item.provider === "mobile_money" && <label>Mobile Money operator<input value={values.network} onChange={e => setValues({ ...values, network: e.target.value })} placeholder="e.g. MTN MoMo or M-Pesa" required={values.enabled} maxLength={80} /><small>Include the account holder, payment currency and any conversion instructions below.</small></label>}<label>User payment instructions<textarea rows={5} required={values.enabled} minLength={values.enabled ? 10 : undefined} maxLength={4000} value={values.instructions} onChange={e => setValues({ ...values, instructions: e.target.value })} /></label><div className="rw-payment-limits"><label>Minimum USD<input inputMode="decimal" value={minimum} onChange={e => setMinimum(e.target.value)} required /></label><label>Maximum USD<input inputMode="decimal" value={maximum} onChange={e => setMaximum(e.target.value)} required /></label></div><label className="rw-check-field"><input type="checkbox" checked={values.enabled} onChange={e => setValues({ ...values, enabled: e.target.checked })} />Accept new deposits with this method</label><label>Reason for configuration change<input value={reason} onChange={e => setReason(e.target.value)} minLength={10} maxLength={500} required /></label>{error && <p className="form-error">{error}</p>}<button className="rw-button rw-button-primary" disabled={busy}>{busy ? "Saving…" : "Save payment configuration"}</button></form></Modal>;
}

function PaymentControl({ profile }: { profile: Profile }) {
  const [controlBusy, setControlBusy] = useState(false); const [controlError, setControlError] = useState("");
  const [methodBusy, setMethodBusy] = useState<string | null>(null); const [methodError, setMethodError] = useState("");
  const path = usePathname(); const [tab, setTab] = useState(path.endsWith("/withdrawals") ? "withdrawals" : "overview"); const [dp, setDp] = useState(1); const [wp, setWp] = useState(1); const [ds, setDs] = useState("pending_review"); const [ws, setWs] = useState("all"); const [channel, setChannel] = useState("all"); const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [deposit, setDeposit] = useState<AdminDeposit | null>(null); const [withdrawal, setWithdrawal] = useState<AdminWithdrawal | null>(null); const [method, setMethod] = useState<PaymentMethod | null>(null);
  const deposits = useResource<PaymentsData>(`/admin/payments?page=${dp}&status=${ds}&channel=${channel}&search=${encodeURIComponent(query)}`); const withdrawals = useResource<Paged<AdminWithdrawal>>(`/admin/payments/withdrawals?page=${wp}&status=${ws}&search=${encodeURIComponent(query)}`); const m = deposits.data?.metrics; const refresh = async () => { await Promise.all([deposits.refresh(), withdrawals.refresh()]); };
  async function toggleAvailability(key: "depositsEnabled" | "withdrawalsEnabled", enabled: boolean) {
    setControlBusy(true); setControlError("");
    try { await api("/admin/payments/availability", { method: "PATCH", body: JSON.stringify({ [key]: !enabled, reason: "Administrator " + (enabled ? "disabled" : "enabled") + " new " + (key === "depositsEnabled" ? "deposits" : "reward withdrawals") + " from payment control." }) }); await refresh(); }
    catch (error) { setControlError((error as Error).message); } finally { setControlBusy(false); }
  }
  async function toggleMethod(item: PaymentMethod) {
    setMethodBusy(item.provider); setMethodError("");
    try {
      await api(`/admin/payments/methods/${item.provider}`, { method: "PATCH", body: JSON.stringify({
        network: item.network, usdRateCents: item.usdRateCents, label: item.label,
        recipient: item.recipient, instructions: item.instructions,
        minimumCents: item.minimumCents, maximumCents: item.maximumCents,
        enabled: !item.enabled,
        reason: `Administrator ${item.enabled ? "disabled" : "enabled"} ${item.label} deposits from payment control.`,
      }) });
      await refresh();
    } catch (error) { setMethodError((error as Error).message); }
    finally { setMethodBusy(null); }
  }
  return <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><div className="ad-page-title"><div><span className="eyebrow">FINANCIAL OPERATIONS</span><h1>Payment control</h1><p>Configure receiving accounts, verify deposits, approve withdrawals, and inspect payment history.</p></div><RefreshButton onClick={refresh} busy={deposits.loading || withdrawals.loading} /></div><div className="ad-payment-tabs">{[["overview", "Overview"], ["deposits", `Deposits${m ? ` (${m.pendingDepositCount})` : ""}`], ["withdrawals", `Withdrawals${m ? ` (${m.openWithdrawalCount})` : ""}`], ["methods", "Payment methods"]].map(([value, label]) => <button key={value} className={tab === value ? "is-active" : ""} onClick={() => setTab(value)}>{label}</button>)}</div><ResourceFeedback {...deposits} retry={deposits.refresh} initial={!deposits.data} />{deposits.data?.availability && <section className="panel"><h2>Accept new requests</h2><p>Turn off either flow at any time. Existing requests remain available for review and completion.</p><div className="rw-inline-actions">{(["depositsEnabled", "withdrawalsEnabled"] as const).map(key => { const enabled = deposits.data!.availability![key]; return <button key={key} type="button" className={enabled ? "rw-button rw-button-secondary" : "rw-button rw-button-primary"} disabled={controlBusy} onClick={() => void toggleAvailability(key, enabled)}>{key === "depositsEnabled" ? "Deposits" : "Reward withdrawals"}: {enabled ? "On ? disable" : "Off ? enable"}</button>; })}</div>{controlError && <p className="form-error" role="alert">{controlError}</p>}</section>}
    {tab === "overview" && m && <><div className="ad-stats ad-payment-stats">{[{ label: "Deposits to review", value: money(m.pendingDepositCents), note: `${m.pendingDepositCount} submissions`, icon: ArrowDownToLine }, { label: "Open withdrawals", value: money(m.openWithdrawalCents), note: `${m.openWithdrawalCount} requests`, icon: Banknote }, { label: "User deposit balances", value: money(m.userDepositCents), note: `${money(m.reservedDepositCents)} reserved`, icon: WalletCards }, { label: "Completed payouts", value: money(m.paidWithdrawalCents), note: `${m.enabledMethodCount} methods enabled`, icon: CheckCircle2 }].map(({ label, value, note, icon: Icon }) => <section className="panel" key={label}><div><span>{label}</span><Icon size={21} /></div><strong>{value}</strong><small>{note}</small></section>)}</div><div className="ad-two-columns"><section className="panel"><h2>Incoming payment queue</h2><p>{m.awaitingPaymentCount} requests await payment and {m.pendingDepositCount} submitted payments need review.</p><button className="rw-button rw-button-primary" onClick={() => setTab("deposits")}>Review deposits</button></section><section className="panel"><h2>Outgoing payment queue</h2><p>{m.openWithdrawalCount} withdrawals totaling {money(m.openWithdrawalCents)} need approval or settlement.</p><button className="rw-button rw-button-secondary" onClick={() => setTab("withdrawals")}>Manage withdrawals</button></section></div><section className="panel ad-section"><div className="section-top"><h2>Receiving method health</h2><button className="rw-button rw-button-secondary" onClick={() => setTab("methods")}><Settings2 size={16} />Configure</button></div><div className="ad-method-strip">{deposits.data?.methods.map(item => <div key={item.provider}><span className={`ad-health ${item.enabled ? "is-live" : ""}`} /><strong>{item.label}</strong><small>{item.enabled ? `${item.network || "Configured"} · ${money(item.minimumCents)}–${money(item.maximumCents)}` : "Disabled"}</small></div>)}</div></section></>}
    {tab === "deposits" && <><form className="ad-toolbar" onSubmit={e => { e.preventDefault(); setQuery(search); setDp(1); }}><input value={search} onChange={e => setSearch(e.target.value)} aria-label="Search deposits" placeholder="Search user, request, or transaction reference" /><select value={ds} onChange={e => { setDs(e.target.value); setDp(1); }}><option value="pending_review">Awaiting review</option><option value="awaiting_payment">Awaiting payment</option><option value="completed">Completed</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option><option value="all">All statuses</option></select><select value={channel} onChange={e => { setChannel(e.target.value); setDp(1); }}><option value="all">All methods</option><option value="USDT">USDT</option><option value="BTC">BTC</option><option value="ETH">ETH</option><option value="mobile_money">Mobile Money</option><option value="bank">Bank</option><option value="paypal">PayPal</option></select><button className="rw-button rw-button-primary"><Search size={16} />Search</button></form><section className="panel"><div className="section-top"><h2>Deposit records</h2><span className="ad-count">{deposits.data?.total || 0}</span></div><div className="ad-table-wrap"><table className="ad-table"><thead><tr><th>User</th><th>Payment</th><th>Amount</th><th>Reference</th><th>Status</th><th>Control</th></tr></thead><tbody>{deposits.data?.items.map(item => <tr key={item.id}><td><strong>{item.user.name}</strong><small>{item.user.email}</small>{item.mobileNumber && <small>Mobile: {item.mobileNumber}</small>}</td><td><strong>{item.asset || item.methodLabel}</strong><small>{item.network || item.provider}</small></td><td><strong>{money(item.amountCents)}</strong><small>{item.asset ? `${item.cryptoAmount} ${item.asset}` : date(item.createdAt)}</small></td><td><span className="ad-reference">{item.paymentReference || "Not submitted"}</span></td><td><span className={`rw-state-badge ${item.status}`}>{paymentStatus(item.status)}</span></td><td><button className="rw-button rw-button-secondary" onClick={() => setDeposit(item)}>Open</button></td></tr>)}</tbody></table></div>{deposits.data?.total === 0 && <div className="rw-empty">No matching deposits.</div>}{deposits.data && <Pagination page={dp} total={deposits.data.total} onPage={setDp} busy={deposits.loading} />}</section></>}
    {tab === "withdrawals" && <><form className="ad-toolbar" onSubmit={e => { e.preventDefault(); setQuery(search); setWp(1); }}><input value={search} onChange={e => setSearch(e.target.value)} aria-label="Search withdrawals" placeholder="Search user, request, or payment reference" /><select value={ws} onChange={e => { setWs(e.target.value); setWp(1); }}><option value="all">All statuses</option><option value="pending">Pending approval</option><option value="approved">Payment due</option><option value="paid">Paid</option><option value="rejected">Rejected</option></select><button className="rw-button rw-button-primary"><Search size={16} />Search</button></form><ResourceFeedback {...withdrawals} retry={withdrawals.refresh} initial={!withdrawals.data} /><section className="panel"><div className="section-top"><h2>Withdrawal records</h2><span className="ad-count">{withdrawals.data?.total || 0}</span></div><div className="ad-table-wrap"><table className="ad-table"><thead><tr><th>User</th><th>Amount</th><th>Source</th><th>Destination</th><th>Status</th><th>Control</th></tr></thead><tbody>{withdrawals.data?.items.map(item => <tr key={item.id}><td><strong>{item.user.name}</strong><small>{item.user.email}</small>{item.mobileNumber && <small>Mobile: {item.mobileNumber}</small>}</td><td><strong>{money(item.amountCents)}</strong><small>{date(item.createdAt)}</small></td><td>{item.source === "points" ? `${points(item.points)} pts` : "Deposit USD"}</td><td><strong>{item.provider.toUpperCase()}</strong><small className="ad-reference">{item.destination}</small></td><td><span className={`rw-state-badge ${item.status}`}>{paymentStatus(item.status)}</span></td><td><button className="rw-button rw-button-secondary" onClick={() => setWithdrawal(item)}>Open</button></td></tr>)}</tbody></table></div>{withdrawals.data?.total === 0 && <div className="rw-empty">No matching withdrawals.</div>}{withdrawals.data && <Pagination page={wp} total={withdrawals.data.total} onPage={setWp} busy={withdrawals.loading} />}</section></>}
    {tab === "methods" && <>{methodError && <p className="form-error" role="alert">{methodError}</p>}<div className="rw-notice"><ShieldCheck size={20} /><p>Only enabled methods appear to users. New requests snapshot the current wallet, network, rate, and instructions.</p></div><div className="ad-method-grid">{deposits.data?.methods.map(item => <section className="panel" key={item.provider}><div className="section-top"><span className="ad-method-icon">{item.provider.startsWith("crypto_") ? <Bitcoin size={22} /> : <Landmark size={22} />}</span><button type="button" role="switch" aria-checked={item.enabled} aria-label={`${item.label} deposits`} className={`ad-method-state ad-method-toggle ${item.enabled ? "is-live" : ""}`} disabled={methodBusy !== null} onClick={() => void toggleMethod(item)}><span className="ad-method-toggle-track" aria-hidden="true"><span /></span>{methodBusy === item.provider ? "Saving..." : item.enabled ? "On" : "Off"}</button></div><h2>{item.label}</h2><p>{item.network || (item.provider === "mobile_money" ? "Mobile Money" : item.provider === "bank" ? "Bank transfer" : "PayPal")}</p><div className="ad-method-address"><small>RECEIVING DESTINATION</small><strong>{item.recipient || "Not configured"}</strong></div><p>Limits: {money(item.minimumCents)} – {money(item.maximumCents)}</p><button className="rw-button rw-button-secondary" onClick={() => setMethod(item)}><Settings2 size={16} />Edit configuration</button></section>)}</div></>}
    {deposit && <DepositReview item={deposit} close={() => setDeposit(null)} saved={refresh} />}{withdrawal && <WithdrawalReview item={withdrawal} close={() => setWithdrawal(null)} saved={refresh} />}{method && <MethodEditor item={method} close={() => setMethod(null)} saved={refresh} />}
  </AdminShell>;
}
export default function Page() { return <AccountGate>{profile => profile.permissions.includes("rewards.manage") ? <PaymentControl profile={profile} /> : <AdminShell name={profile.user.name} roles={profile.roles} permissions={profile.permissions}><h1>Administrator access required.</h1></AdminShell>}</AccountGate>; }
